<?php
	//-- Stylesheets --//
	echo $this->tag->stylesheetLink("https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,800italic,300,400,600,800", false);
	//echo $this->tag->stylesheetLink("https://fonts.googleapis.com/css?family=Open+Sans:300italic,600italic,800italic,300,600,800", false);
	echo $this->tag->stylesheetLink("css/canvas-admin/font-awesome.min.css");
	echo $this->tag->stylesheetLink("css/canvas-admin/bootstrap.min.css");
	echo $this->tag->stylesheetLink("js/canvas-admin/libs/css/ui-lightness/jquery-ui-1.9.2.custom.css");
	echo $this->tag->stylesheetLink("js/canvas-admin/plugins/magnific/magnific-popup.css");
	echo $this->tag->stylesheetLink("css/canvas-admin/App.css");
	echo $this->tag->stylesheetLink("css/canvas-admin/custom.css");
	echo $this->tag->stylesheetLink("css/jquery.fileupload.css");
	
?>