<?php

//-- Page Vars --//
$page_title = 'Page Not Found';


	//-- Pull in Header --//
	Phalcon\Tag::appendTitle($page_title);
	$this->partial("partials/header-top");
	$this->partial("partials/styles/default");
	$this->partial("partials/header-bottom");

	//-- Page Content Title --//
	echo '<div id="content-header"><h1>'.$page_title.'</h1></div><!-- #content-header -->';

	//-- Page Content --// ?>
	<div id="content-container">
		
		<?php $this->flashSession->output(); ?>
		
		<div class="row">
			<div class="col-md-12">
				<div class="error-container">

					<div class="error-code">
						404
					</div> <!-- /.error-code -->

					<div class="error-details">
						<h4>Oops, You're lost.</h4>
						<p>We can not find the page you're looking for.<br />
						   Try the buttons below or the links in the sidebar.
						</p>
						<p>
							<?php
								$gradeBtnTxt = 'Grade Students';
								//-- Figure out link for grading students --//
								if($this->session->get("user-role") == 100){
									$gradeBtnTxt = 'Grade Yourself';
									$link = '/grading/students';
								}else if($this->session->get("user-role") == 5){
									$link = '/grading/parents';
								}else{
									$link = '/grading/staff';
								}
							?>
							<a href="<?php echo $link; ?>" class="btn btn-primary" style="margin-right: 5px;"><i class="fa fa-check"></i> <?php echo $gradeBtnTxt; ?></a>
							<?php
								//-- show curriculum button if coach or admin --//
								if($this->session->get("user-role") <= 2 || $this->session->get("user-role") == 4){ ?>
									<a href="/traits" class="btn btn-secondary"><i class="fa fa-trophy"></i> Approved Curriculum</a><?php
								}
								//-- Buttons for students --//
								if($this->session->get("user-role") == 100){ ?>
									<a href="/resources" class="btn btn-secondary"><i class="fa fa-download"></i> Resources</a><?php
								}
							?>
							
						</p>
					</div> <!-- /.error-details -->

				</div> <!-- /.error -->
			</div> <!-- /.col-md-12 -->
		</div> <!-- /.row -->
		
		
	</div>

<?php
//-- Footer --//
$this->partial("partials/footer-top");
$this->partial("partials/scripts/default");
$this->partial("partials/footer-bottom");
?>