<?php

//-- PHP Includes --//
include "inc/states.php";

//-- Page Vars --//
$page_title = 'Class Roster';


	//-- Pull in Header --//
	Phalcon\Tag::appendTitle($page_title);
	$this->partial("partials/header-top");
	$this->partial("partials/styles/default");
	$this->partial("partials/header-bottom");

	//-- Page Content Title --//
	echo '<div id="content-header"><h1>'.$page_title.'</h1></div><!-- #content-header -->';

	//-- Page Content --// ?>
	<div id="content-container">
		
		<?php $this->flashSession->output(); ?>
		
		<div id="controlBar" class="col-md-12">
			<!-- add User Btn -->
			<?php
				if(!isset($schoolID) || !$schoolID){
					//-- Do Nothing --//
				}else{
					if($cap['rosters']['add-to-roster']){ ?>
						<span id="student-roster-add" class="btn btn-primary" title="Add Student to Roster" style="margin-right: 5px;"><i class="fa fa-plus"></i> &nbsp;Add Student</span>
					<?php }
				}
			?>
			
			<?php
			//-- Show / Hide Filters --//
			if(((isset($schoolID) && $schoolID) && $this->session->get("user-role") <= 3) || isset($gradeID) || isset($periodID) || (isset($coachID) && $this->session->get("user-role") != 6) || (isset($searchTerm) && $searchTerm)){
				$filterText = 'Hide Filters';
				$showFilters = 'style="display: block;"';
			}else if(!isset($schoolID) || !$schoolID){
				$filterText = 'Hide Filters';
				$showFilters = 'style="display: block;"';
			}else{
				$filterText = 'Show Filters';
				$showFilters = '';
			} ?>
			<div id="show-user-filters" class="btn-group" title="Filters" style="margin-right: 5px;">
				<a href="#" class="btn btn-secondary"><i class="fa fa-filter"></i> <span><?php echo $filterText; ?></span></a>
			</div>
			
			<!-- Refresh Button -->
			<div class="btn-group" title="Refresh Page" style="margin-right: 5px;">
				<form id="refresh-page" action="" method="post">
					<span class="btn btn-success" id="refresh-ctrl-btn" onclick="jQuery('#refresh-page').submit();"><i class="fa fa-refresh"></i> <span>Refresh</span></span>
					<?php echo $inputs.$filters; ?>
				</form>
			</div>
			
			<!-- Filters -->
			<div id="user-filters" class="well" <?php echo $showFilters; ?>>
				<?php //-- school filter --//
				if($schools && $this->session->get("user-role") <= 3){ ?>
					<div class="filter-school col-sm-6">
						<form id="schoolFilter" action="" method="post">
							<label for="filter-schools">School Filter</label>
							<select name="filterSchool" id="filter-schools" class="form-control" onchange="jQuery('#schoolFilter').submit();">
								<option value="">Select School</option>
								<?php
									//-- List Out Schools --//
									$curState = '';
									foreach($schools as $school){
										if($school->state != $curState){
											if($curState){
												echo '</optgroup><optgroup label="'.$states[$school->state].'">';
											}else{
												echo '<optgroup label="'.$states[$school->state].'">';
											}
											$curState = $school->state;
										}
										if(isset($schoolID) && $school->id == $schoolID){ $sel = 'selected="selected"'; }else{ $sel = ''; }
										echo '<option value="'.$school->id.'" '.$sel.'>'.$school->schoolName.' ('.$school->city.', '.$school->state.')</option>';
									}
									echo '</optgroup>';
								?>
							</select>
							<?php echo $inputs.$coachFilter.$gradeFilter.$periodFilter.$searchFilter; ?>
						</form>
					</div><?php
				}
				
				//-- grade filter --//
				if(isset($grade_level) && $grade_level){ ?>
					<div class="filter-grade col-sm-6">
						<form id="gradeFilter" action="" method="post">
							<label for="filter-grade">Grade Level Filter</label>
							<select name="filterGrade" id="filter-grade" class="form-control" onchange="jQuery('#gradeFilter').submit();">
								<option value="">Select Grade Level</option>
								<?php
									//-- List Out Grade Levels --//
									foreach($grade_level as $grade){
										if(isset($gradeID) && $grade->id == $gradeID){ $sel = 'selected="selected"'; }else{ $sel = ''; }
										echo '<option value="'.$grade->id.'" '.$sel.'>'.$grade->gradeName.'</option>';
									}
								?>
							</select>
							<?php echo $inputs.$schoolFilter.$coachFilter.$periodFilter.$searchFilter ?>
						</form>
					</div><?php
				}
				
				//-- coach filter --//
				if(isset($coachList) && $this->session->get("user-role") != 6){ ?>
					<div class="filter-coach col-sm-6" <?php if($this->session->get("user-role") <= 3){ echo 'style="margin-top: 10px;"'; } ?>>
						<form id="coachFilter" action="" method="post">
							<label for="filter-coach">Athletic Coach Filter</label>
							<select name="filterCoach" id="filter-coach" class="form-control" onchange="jQuery('#coachFilter').submit();">
								<option value="">Select Coach</option>
								<?php
									//-- List Out Coaches --//
									foreach($coachList as $coach){
										if(isset($coachID) && $coach->id == $coachID){ $sel = 'selected="selected"'; }else{ $sel = ''; }
										echo '<option value="'.$coach->id.'" '.$sel.'>'.$coach->lname.', '.$coach->fname.'</option>';
									}
								?>
							</select>
							<?php echo $inputs.$schoolFilter.$gradeFilter.$periodFilter.$searchFilter; ?>
						</form>
					</div><?php
				} ?>
				
				<!-- Class Period Filter -->
				<div class="filter-period col-sm-6" <?php if($this->session->get("user-role") != 6){ echo 'style="margin-top: 10px;"'; } ?>>
					<form id="periodFilter" action="" method="post">
						<label for="class-period">Class Period</label>
						<select name="class-period" id="class-period" class="form-control" onchange="jQuery('#periodFilter').submit();">
							<option value="">Show All Periods</option><?php
							$x = 1;
							while($x < 11){
								if(isset($periodID) && $periodID == $x){ $sel = 'selected="selected"'; }else{ $sel = ''; }
								echo '<option value="'.$x.'" '.$sel.'>Period '.$x.'</option>';
								$x++;
							} ?>
							<option value="0" <?php if(isset($periodID) && $periodID == 0){ echo 'selected="selected"'; } ?>>Unassigned</option>
							
						</select>
						<?php echo $inputs.$schoolFilter.$coachFilter.$gradeFilter.$searchFilter ?>
					</form>
				</div>
				
				<!-- Search Filter -->
				<div id="filter-search" class="col-sm-6" style="margin-top: 10px;">
					<form id="searchFilter" action="" method="post">
						<label for="searchTerm">Search for Student In Roster</label>
						<div class="input-group">
							<input type="text" name="filterSearch" id="searchTerm" class="form-control" placeholder="Enter First or Last Name" value="<?php if(isset($searchTerm) && $searchTerm != ''){ echo $searchTerm; } ?>">
							<div class="input-group-btn">
								<button type="button" id="quick-search" class="btn btn-tertiary" onclick="jQuery('#searchFilter').submit();"><i class="fa fa-search"></i> Search</button>
							</div><!-- /input-group-btn -->
						</div><!-- /input-group -->
						<?php echo $inputs.$schoolFilter.$coachFilter.$gradeFilter.$periodFilter; ?>
					</form>
				</div>
				<!-- End Search Filter -->
				<div class="clear"></div>
			</div>
			<!-- end filters -->
		</div><!-- /#controlBar -->
		
		<div id="display-results" class="col-md-12">
			<?php
			if(!isset($schoolID) || !$schoolID){
				echo '<div class="alert alert-danger">To view enrolled students on the roster, please select a school first.</div>';
			}else{ ?>
				<div class="table-responsive">
				
					<table class="table table-hover table-bordered">
						<thead>
							<tr>
								<th style="width: 30px;">
									<input type="checkbox" id="check-all" />
								</th>
								<th>
									<form id="form1" action="" method="post">
										<input type="hidden" name="field" value="firstname" />
										<span onclick="jQuery('#form1').submit();">First Name</span>
										<?php
										echo $lastField;
										if($field == 'firstname'){ echo '<i class="fa fa-sort-'.$dir.'"></i>'; }
										?>
									</form>
								</th>
								<th>
									<form id="form2" action="" method="post">
										<input type="hidden" name="field" value="lastname" />
										<span onclick="jQuery('#form2').submit();">Last Name</span>
										<?php
										echo $lastField;
										if($field == 'lastname'){ echo '<i class="fa fa-sort-'.$dir.'"></i>'; }
										?>
									</form>
								</th>
								<th class="hideable">
									<form id="form3" action="" method="post">
										<input type="hidden" name="field" value="class" />
										<span onclick="jQuery('#form3').submit();">Period</span>
										<?php
										echo $lastField;
										if($field == 'class'){ echo '<i class="fa fa-sort-'.$dir.'"></i>'; }
										?>
									</form>
								</th>
								<th class="hideable">
									<form id="form4" action="" method="post">
										<input type="hidden" name="field" value="grade_level" />
										<span onclick="jQuery('#form4').submit();">Grade</span>
										<?php
										echo $lastField;
										if($field == 'grade_level'){ echo '<i class="fa fa-sort-'.$dir.'"></i>'; }
										?>
									</form>
								</th>
								<?php
								if($this->session->get("user-role") <= 3){ ?>
									<th class="hideable">
										<form id="form5" action="" method="post">
											<input type="hidden" name="field" value="school" />
											<span onclick="jQuery('#form5').submit();">School</span>
											<?php
											echo $lastField;
											if($field == 'school'){ echo '<i class="fa fa-sort-'.$dir.'"></i>'; }
											?>
										</form>
									</th><?php
								}
								if($this->session->get("user-role") != 6){ ?>
									<th class="hideable">
										<form id="form6" action="" method="post">
											<input type="hidden" name="field" value="coach" />
											<span onclick="jQuery('#form6').submit();">Coach</span>
											<?php
											echo $lastField;
											if($field == 'coach'){ echo '<i class="fa fa-sort-'.$dir.'"></i>'; }
											?>
										</form>
									</th><?php
								} ?>
								<th></th>
							</tr>
						</thead>
						<tbody>
							<?php
							if(count($students) > 0){
								foreach($students as $student){ ?>
									<tr>
										<td style="width: 30px;">
											<input type="checkbox" class="select-check" name="select-user[]" value="<?php echo $student->id; ?>" />
										</td>
										<td><?php echo $student->fname; ?></td>
										<td><?php echo $student->lname; ?></td>
										<td class="hideable"><?php echo $student->turf_period; ?></td>
										<td><?php echo $student->grade; ?></td>
										<?php
										if($this->session->get("user-role") <= 3){
											//-- School Name Abbreviation --//
											if(isset($school_abbreviations) && isset($school_abbreviations[$student->school])){ ?>
												<td class="hideable"><?php echo $school_abbreviations[$student->school]; ?></td><?php
											}else{ ?>
												<td class="hideable">N/A</td><?php
											}
										}
										if($this->session->get("user-role") != 6){
											//-- Coach Name --//
											if(isset($coachRef) && !empty($coachRef) && isset($coachRef[$student->coach])){ ?>
												<td class="hideable"><?php echo $coachRef[$student->coach]; ?></td><?php
											}else{ ?>
												<td class="hideable"><?php echo $student->coach; ?></td><?php
											}
										} ?>
										<td>
											<?php $user_name = $student->fname.' '.$student->lname; ?>
											<?php if($cap['rosters']['edit']){ ?>
												<span class="label label-secondary editStudent" data-student-val="<?php echo $student->id; ?>"><i class="fa fa-pencil"></i> Edit</span>
											<?php } ?>
											<?php if($cap['rosters']['remove']){ ?>
												<span class="label label-tertiary removeStudent" data-student-val="<?php echo $student->id; ?>" data-student-name="<?php echo $user_name; ?>"><i class="fa fa-ban"></i> Remove</span>
											<?php } ?>
										</td>
									</tr><?php
								}
							}else{
								if($this->session->get("user-role") <= 3){ ?>
									<tr><td colspan="8">No Results</td></tr><?php
								}else if($this->session->get("user-role") != 6){ ?>
									<tr><td colspan="7">No Results</td></tr><?php
								}else{ ?>
									<tr><td colspan="6">No Results</td></tr><?php
								}
							} ?>
						</tbody>
					</table>
				
				</div><!-- /.table-responsive --> <?php
			} ?>
		</div><!-- /#display-results -->
		
		<div class="col-md-12">
			
			<?php
			//-- Create Pager --//
			if($totalStudents){
				echo '<div class="users-pager">';
				echo '<span class="page-count">Showing '.$totalStudents.' Students</span>';
				echo '</div>'; ?>
				<?php
			} ?>
			
		</div>
		
	</div><!-- /#content-container -->

<?php
	//-- Footer --//
	$this->partial("partials/footer-top");
	$this->partial("partials/scripts/manage-class-roster");
	$this->partial("partials/footer-bottom");
?>