<?php

//-- Page Vars --//
$page_title = 'Student Resources';


	//-- Pull in Header --//
	Phalcon\Tag::appendTitle($page_title);
	$this->partial("partials/header-top");
	$this->partial("partials/styles/default");
	$this->partial("partials/header-bottom");

	//-- Page Content Title --//
	echo '<div id="content-header"><h1>'.$page_title.'</h1></div><!-- #content-header -->';

	//-- Page Content --// ?>
	<div id="content-container">
		
		<?php $this->flashSession->output(); ?>
		
		<div class="col-md-3 col-sm-5">
			<!-- Stacked Tabs - Navigation -->
			<ul class="nav nav-pills nav-stacked">
				<li class="active">
					<a href="#resources-settings" data-toggle="tab"><i class="fa fa-gears"></i> &nbsp;&nbsp;Settings</a>
				</li>
				<li>
					<a href="#manage-docs" data-toggle="tab"><i class="fa fa-download"></i> &nbsp;&nbsp;Manage Downloads</a>
				</li>
				<li>
					<a href="#upload-docs" data-toggle="tab"><i class="fa fa-upload"></i> &nbsp;&nbsp;Upload Documents</a>
				</li>
			</ul>

		</div><!-- /.col -->

		<div class="col-md-9 col-sm-7">

			<div class="tab-content stacked-content">
				
				<div class="tab-pane fade in active" id="resources-settings">
					<div id="resource-controls">
						<h3><i class="fa fa-gears"></i> Settings</h3>
						<div id="resource-passcode" class="form-group">
							<label for="resource-password">Student Resource Password</label><br />
							<input type="text" id="resource-password" class="form-control" value="" placeholder="Enter Resources Password..." />
							<span class="btn btn-primary" id="updatePasscode">Update</span>
						</div>
					</div>
				</div>
				
				<div class="tab-pane fade" id="manage-docs">
					<div id="manage-downloads">
						<h3 class="heading"><i class="fa fa-download"></i> Manage Downloads</h3>
						
						<?php
							//-- Echo out contents of Amazon Bucket --//
							if(isset($bucket_contents) && $bucket_contents){
								foreach($bucket_contents as $file){
								    $fname = $file['name'];
								    $furl = "http://athlos-tools-resources.s3.amazonaws.com/".$fname;
									$fsize = $file['size'];
									$ext = strtolower(pathinfo($fname, PATHINFO_EXTENSION));
									
									//-- determine what class to use --//
									if($ext == 'doc' || $ext == 'docx'){
										$useClass = 'download-word';
									}else{
										$useClass = 'download-doc';
									}
									
								    //-- Output link to file --//
									echo '<div class="download '.$useClass.'">';
								    echo '<a href="'.$furl.'">'.$fname.'</a>';
									echo '<span class="docsize">('.round($fsize / 1024, 1).' KB)</span>';
									echo '<span class="btn btn-xs btn-primary delete-doc" data-name="'.$fname.'" style="margin: 0 0 0 30px;"><i class="fa fa-times"></i> Remove</span>';
									echo '</div>';
								}
							}
						?>
					</div>
				</div>
				
				<div class="tab-pane fade" id="upload-docs">
					<div id="upload-documents">
						<h3 class="heading"><i class="fa fa-upload"></i> Upload Documents</h3>
						
						<p>
							Select the file that you would like to upload into the list of uploaded resource documents, Please ensure that the file you are uploading is a pdf or word document:
						</p>

						<!-- Upload PDF to Amazon Bucket Form -->
						<form id="upload-resource-form" action="" method="post" enctype="multipart/form-data">
							<input type="hidden" name="action" value="upload_resource" />
							<p>
								<span class="btn btn-primary fileinput-button">
						        	<i class="glyphicon glyphicon-plus"></i>
						        	<span>Select Document</span>
						        	<!-- The file input field used as target for the file upload widget -->
						        	<input id="resourceupload" type="file" name="theFile">
						    	</span>
								<span id="document-to-upload">
									<span class="the-doc-name"></span>
								</span>
								<span id="res-up-err" class="alert alert-danger"></span>
							</p>
						    <p>
						    	<input type="submit" id="upload-doc" class="btn btn-primary" value="Upload" />
							</p>
						</form>
						
					</div>
				</div>
				
			</div>

		</div> <!-- /.col -->
		
	</div><!-- end #content-container -->

<?php
	//-- Footer --//
	$this->partial("partials/footer-top");
	$this->partial("partials/scripts/student-resources");
	$this->partial("partials/footer-bottom");
?>