<?php

//-- Page Vars --//
$page_title = 'Athletic Curriculum';


	//-- Pull in Header --//
	Phalcon\Tag::appendTitle($page_title);
	$this->partial("partials/header-top");
	$this->partial("partials/styles/athletic-curriculum");
	$this->partial("partials/header-bottom");

	//-- Page Content Title --//
	echo '<div id="content-header"><h1>'.$page_title.'</h1></div><!-- #content-header -->';

	//-- Page Content --// ?>
	<div id="content-container">
		
		<?php $this->flashSession->output(); ?>
		
		<div id="manage-downloads" style="margin: 40px;">
			<?php
				if(isset($folders) && $folders){
					$folderCount = count($folders);
					$missedFolders = 0; ?>
					<div class="row">
						<div class="col-md-3 col-sm-4">
							<ul id="myTab" class="nav nav-pills nav-stacked"><?php
								$pillCount = 1;
								foreach($folders as $folderID => $folder_contents){
									//-- Validate user can view the folder --//
									if(($this->session->get('user-role') == 1) || ($this->session->get("user-district") !== null && (in_array($this->session->get("user-district"), $folder_contents['permissions']) || in_array('all', $folder_contents['permissions'])))){
										if($folderID != 'name' && $folderID != 'url' && $folderID != 'icon' && $folderID != 'permissions'){ ?>
											<li <?php if($pillCount == 1){ echo 'class="active"'; } ?>>
									        	<a href="#unit-<?php echo $folderID; ?>-contents" data-toggle="tab">
									        		<i class="fa <?php if(isset($folder_contents['icon'])){ echo $folder_contents['icon']; }else{ echo 'fa-folder-open'; } ?>"></i> 
									        		&nbsp;&nbsp;<?php echo $folder_contents['name']; ?>
									        	</a>
									        </li><?php
											$pillCount++;
										}
									}
								} ?>
							</ul>
						</div><!-- /.col -->
						
						<div class="col-md-9 col-sm-8">
						      <div class="tab-content stacked-content">

								<?php
								//-- Lesson Navigation --//
								$panelCount = 1;
								foreach($folders as $folderID => $folder_contents){
									//-- Validate user can view the folder --//
									if(($this->session->get('user-role') == 1) || ($this->session->get("user-district") !== null && (in_array($this->session->get("user-district"), $folder_contents['permissions']) || in_array('all', $folder_contents['permissions'])))){
										if($folderID != 'name' && $folderID != 'url' && $folderID != 'icon' && $folderID != 'permissions'){ ?>
											<div class="tab-pane fade <?php if($panelCount == 1){ echo 'in active'; } ?>" id="unit-<?php echo $folderID; ?>-contents">
								
												<div class="col-md-12">
												    <h3><?php echo '<i class="fa '.$folder_contents['icon'].'"></i> &nbsp;'.$folder_contents['name']; ?></h3>
									
													<label for="innerTabs-<?php echo $folderID; ?>">Lesson Topic</label><br />
													<select id="innerTabs-<?php echo $folderID; ?>" class="lesson-nav form-control">
														<option value="">Select Lesson Topic</option><?php
															foreach($folder_contents as $subfolder => $subfolder_contents){
																if($subfolder != 'name' && $subfolder != 'url' && $subfolder != 'icon' && $subfolder != 'permissions'){
																	//-- Validate user can view the folder --//
																	if(($this->session->get('user-role') == 1) || ($this->session->get("user-district") !== null && (in_array($this->session->get("user-district"), $subfolder_contents['permissions']) || in_array('all', $subfolder_contents['permissions'])))){ ?>
   																		<option value="#folder-unit-<?php echo $subfolder; ?>"><?php echo $subfolder_contents['name']; ?></option><?php
																	}
																}
															} ?>
													</select>
									
													<div id="unit-<?php echo $subfolder; ?>-tab-nav" class="tab-content" style="margin: 15px 0 0; padding: 20px 0 0; border-top: 1px dashed #eaeaea;"><?php
														//-- List out lessons by topic --//
														$num = 0;
														foreach($folder_contents as $subfolder => $subfolder_contents){
															if($subfolder != 'name' && $subfolder != 'url' && $subfolder != 'icon' && $subfolder != 'permissions'){
																//-- Validate user can view the folder --//
																if(($this->session->get('user-role') == 1) || ($this->session->get("user-district") !== null && (in_array($this->session->get("user-district"), $subfolder_contents['permissions']) || in_array('all', $subfolder_contents['permissions'])))){ ?>
																	<div class="tab-pane fade" id="folder-unit-<?php echo $subfolder; ?>">
																		<h4 style="padding-bottom: 8px; border-bottom: 2px solid #e1e1e1;"><?php echo '<i class="fa '.$subfolder_contents['icon'].'"></i> &nbsp;'.$subfolder_contents['name']; ?></h4>
																		<?php
																		foreach($subfolder_contents[0] as $file){
																		    $fname = $file['name'];
																			$fileNameArr = explode('/', $file['name']);
																			$trimmedName = array_pop($fileNameArr);
																		    $furl = "http://athlos-tools.s3.amazonaws.com/".$fname;
																			$fsize = $file['size'];
																			$ext = strtolower(pathinfo($fname, PATHINFO_EXTENSION));
																			$newName = str_ireplace('.'.$ext, '', $fname);

																			//-- determine what class to use --//
																			if($ext == 'doc' || $ext == 'docx'){
																				$useClass = 'download-word';
																			}else if($ext == 'zip'){
																				$useClass = 'download-zip';
																			}else if($ext == 'xls' || $ext == 'xlsx'){
																				$useClass = 'download-xls';
																			}else{
																				$useClass = 'download-doc';
																			}

																		    //-- Output link to file --//
																			echo '<div class="'.$useClass.'" style="margin: 0; padding: 18px 0 17px 60px; background-position: 0 10px; background-size: 40px;">';
																		    //echo '<a href="'.$furl.'">'.$trimmedName.'</a>';
																			
																		    echo '<a href="/athletic/viewer/?name='.urlencode($trimmedName).'&path='.urlencode(str_ireplace('http:', 'https:', $furl)).'" target="_blank">'.$trimmedName.'</a>';						
																			echo '<span style="margin: 0 0 0 10px; color: #808080;">('.round($fsize / 1024, 1).' KB)</span>';
																			//echo '<span onclick="location.href = \''.$furl.'\'" class="btn btn-xs btn-primary" style="margin: 0 0 0 30px;"><i class="fa fa-download"></i> &nbsp;Download</span>';
																			echo '<span onclick="window.open(\'/athletic/viewer/?name='.urlencode($trimmedName).'&path='.urlencode(str_ireplace('http:', 'https:', $furl)).'\');" class="btn btn-xs btn-primary" style="margin: 0 0 0 30px;"><i class="fa fa-eye"></i> &nbsp;View</span>';
																			echo '</div>';
																		} ?>
																	</div> <!-- /.tab-pane --><?php
																	$num++;
																}
															}
														} ?>
													</div> <!-- /.tab-content -->
												</div> <!-- /.col -->
								
											</div> <!-- /.tab-pane --><?php
											$panelCount++;
										}
									}
								} ?>
							
						      </div> <!-- /.stacked-content -->
						</div> <!-- /.col -->
					</div><!-- /.row -->
					<?php
				} ?>
		</div><!-- /#manage-downloads -->
		
	</div><!-- end #content-container -->

<?php
	//-- Footer --//
	$this->partial("partials/footer-top");
	$this->partial("partials/scripts/athletic-curriculum");
	$this->partial("partials/footer-bottom");
?>