<?php

//-- Page Vars --//
$page_title = 'Athletic Curriculum';


	//-- Pull in Header --//
	Phalcon\Tag::appendTitle($page_title);
	$this->partial("partials/header-top");
	$this->partial("partials/styles/default");
	$this->partial("partials/header-bottom");

	//-- Page Content Title --//
	echo '<div id="content-header"><h1>'.$page_title.'</h1></div><!-- #content-header -->';

	//-- Page Content --// ?>
	<div id="content-container">
		
		<?php $this->flashSession->output(); ?>
		
		<div id="manage-downloads" style="margin: 40px;">
			<h3>Select Curriculum Level</h3>
			<?php
				//-- Echo out contents of Amazon Bucket --//
				if(isset($bucket_contents) && $bucket_contents){
					echo '<div class="panel-group accordion" id="accordion">';
					$textArr = array(1 => 'One', 2 => 'Two', 3 => 'Three', 4 => 'Four');
					foreach($bucket_contents as $level_key => $level_contents){ ?>
						
							<div class="panel panel-default">
								<div class="panel-heading">
									<h4 class="panel-title">
										<a class="accordion-toggle" data-toggle="collapse" data-parent=".accordion" href="#collapse<?php echo $textArr[$level_key]; ?>">
										Level <?php echo $level_key; ?>
										</a>
									</h4>
								</div>

								<div id="collapse<?php echo $textArr[$level_key]; ?>" class="panel-collapse collapse">
									<div class="panel-body"><?php
										foreach($level_contents as $file){
										    $fname = $file['name'];
										    $furl = "http://athlos-tools-athletic-level-".$level_key.".s3.amazonaws.com/".$fname;
											$fsize = $file['size'];
											$ext = strtolower(pathinfo($fname, PATHINFO_EXTENSION));

											//-- determine what class to use --//
											if($ext == 'doc' || $ext == 'docx'){
												$useClass = 'download-word';
											}else if($ext == 'zip'){
												$useClass = 'download-zip';
											}else if($ext == 'xls' || $ext == 'xlsx'){
												$useClass = 'download-xls';
											}else{
												$useClass = 'download-doc';
											}

										    //-- Output link to file --//
											echo '<div class="'.$useClass.'">';
										    echo '<a href="'.$furl.'">'.$fname.'</a>';
											echo '<span style="margin: 0 0 0 10px; color: #808080;">('.round($fsize / 1024, 1).' KB)</span>';
											echo '<span onclick="location.href = \''.$furl.'\'" class="btn btn-xs btn-primary" style="margin: 0 0 0 30px;"><i class="fa fa-download"></i> &nbsp;Download</span>';
											echo '</div>';
										} ?>
									</div>
								</div>
							</div> <!-- /.panel-default --> <?php
					}
					echo '</div> <!-- /.accordion -->';
				}
			?>
		</div>
		
	</div><!-- end #content-container -->

<?php
	//-- Footer --//
	$this->partial("partials/footer-top");
	$this->partial("partials/scripts/default");
	$this->partial("partials/footer-bottom");