<?php
/**
 * Athleticism Improvement Report & Athletic Data Export Script
 */

//-- PHP Includes --//
include "inc/states.php";

//-- Page Vars --//
$page_title = 'Athleticism Improvement Reports';


	//-- Pull in Header --//
	Phalcon\Tag::appendTitle($page_title);
	$this->partial("partials/header-top");
	$this->partial("partials/styles/default");
	$this->partial("partials/header-bottom");

	//-- Page Content Title --//
	echo '<div id="content-header"><h1>'.$page_title.'</h1></div><!-- #content-header -->';

	//-- Page Content --// ?>
	<div id="content-container">
		
		<?php $this->flashSession->output(); ?>
		
		<!-- Filters -->
		<div id="user-filters" class="well" <?php echo 'style="display: block;"'; ?>>
			<!-- Assessment Filter -->
			<div class="col-sm-6">
				<div class="form-group">	
					<label for="filter-assessments">Assessment *</label>
					<select id="filter-assessments" name="filterAssessments" class="form-control" data-required="true">
						<option value="">Select Assessment</option><?php
							$assessments = AthleticAssessments::find('');
							if(!empty($assessments)){
								foreach($assessments as $test){
									if($test->data_label == 'Sec.'){ $newLabel = 'Seconds'; }else if($test->data_label == 'In.'){ $newLabel = "Inches"; }else{ $newLabel = $test->data_label; }
									echo '<option value="'.$test->url_name.'" data-type="'.$test->type.'" data-measure="'.$test->data.'" data-label="'.$newLabel.'">'.$test->assessment_name.'</option>';
								}
							}
						?>
					</select>
				</div>
			</div><!-- /.col -->
			<?php
			 //-- school filter --//
			if (!empty($schools)) { ?>
				<div class="col-sm-6">
					<div class="form-group">
						<label for="filter-schools">School</label>
						<select name="filterSchool" id="filter-schools" class="form-control">
							<option value="">All Schools</option>
							<?php
								//-- List Out Schools --//
								$curState = '';
								foreach($schools as $school){
									if($school->state != $curState){
										if($curState){
											echo '</optgroup><optgroup label="'.$states[$school->state].'">';
										}else{
											echo '<optgroup label="'.$states[$school->state].'">';
										}
										$curState = $school->state;
									}
									if(isset($schoolID) && $school->id == $schoolID){ $sel = 'selected="selected"'; }else{ $sel = ''; }
									echo '<option value="'.$school->id.'" '.$sel.'>'.$school->schoolName.' ('.$school->city.', '.$school->state.')</option>';
								}
								echo '</optgroup>';
							?>
						</select>
					</div><!-- /.form-group -->
				</div><?php
			}
			//-- grade filter --//
			if(isset($grade_level) && $grade_level){ ?>
				<div class="col-sm-6">
					<div class="form-group">
						<label for="filter-grade">Grade Level</label>
						<select name="filterGrade" id="filter-grade" class="form-control">
							<option value="">Select Grade Level</option>
							<?php
								//-- List Out Grade Levels --//
								foreach($grade_level as $grade){
									if(isset($gradeID) && $grade->id == $gradeID){ $sel = 'selected="selected"'; }else{ $sel = ''; }
									echo '<option value="'.$grade->id.'" '.$sel.'>'.$grade->gradeName.'</option>';
								}
							?>
						</select>
					</div><!-- /.form-group -->
				</div><?php
			} ?>
			
			<div class="col-sm-6">
				<div class="form-group">
					<label for="filter-growth">Growth Period *</label>
					<select name="filterGrowth" id="filter-growth" class="form-control">
						<?php
							$growthArr = array(2 => 'Over 2 Year Span', 3 => 'Over 3 year Span');
							//-- List Out Growth --//
							foreach($growthArr as $growth => $g_text){
								echo '<option value="'.$growth.'">'.$g_text.'</option>';
							}
						?>
					</select>
				</div><!-- /.form-group -->
			</div>
			
			<div class="col-sm-12 text-center clear">
				<span id="get-report" class="btn btn-secondary">Run Report &nbsp;<i class="fa fa-arrow-right"></i></span>
			</div>
			
			<div class="clear"></div>
		</div>
		<!-- end filters -->

		<div class="row">
			<div class="col-xs-12">
				<div id="display-results" style="margin-top: 30px;"></div>
			</div><!-- /.col -->
		</div><!-- /.row -->
		


		<h2 class="margin-top-60">Export Athletic Data</h2>
		<blockquote>Use this report to pull the athletic data per campus.</blockquote>
		<div id="export-filters" class="well" <?php echo 'style="display: block;"'; ?>>
			<?php
			 //-- campus filter --//
			if (!empty($schools)) { ?>
				<div class="col-sm-4">
					<div class="form-group">
						<label for="filter-campus">Campus</label>
						<select name="filterCampus" id="filter-campus" class="form-control">
							<option value="">Select Campus</option>
							<?php
								//-- List Out School Campuses --//
								$curState = '';
								foreach($schools as $school){
									if($school->state != $curState){
										if($curState){
											echo '</optgroup><optgroup label="'.$states[$school->state].'">';
										}else{
											echo '<optgroup label="'.$states[$school->state].'">';
										}
										$curState = $school->state;
									}
									if(isset($schoolID) && $school->id == $schoolID){ $sel = 'selected="selected"'; }else{ $sel = ''; }
									echo '<option value="'.$school->id.'" '.$sel.'>'.$school->schoolName.' ('.$school->city.', '.$school->state.')</option>';
								}
								echo '</optgroup>';
							?>
						</select>
					</div><!-- /.form-group -->
				</div><?php
			}
			//-- grade filter --//
			if (!empty($school_years)) { ?>
				<div class="col-sm-4">
					<div class="form-group">
						<label for="filter-year">School Year</label>
						<select name="filterYear" id="filter-year" class="form-control">
							<option value="">Select School Year</option>
							<?php
								//-- List Out Available School Years --//
								foreach($school_years as $year){
									echo '<option value="'.$year->id.'">'.$year->semesterName.'</option>';
								}
							?>
						</select>
					</div><!-- /.form-group -->
				</div><?php
			} ?>
			
			<div class="col-sm-4">
				<div class="form-group">
					<label for="filter-phase">Testing Phase</label>
					<select name="filterPhase" id="filter-phase" class="form-control">
						<?php
							$phaseArr = array('all' => 'All Phases', 1 => 'Phase 1', 2 => 'Phase 2');
							//-- List Out Growth --//
							foreach($phaseArr as $phase => $phaseName){
								echo '<option value="'.$phase.'">'.$phaseName.'</option>';
							}
						?>
					</select>
				</div><!-- /.form-group -->
			</div>
			
			<div class="col-sm-12 text-center clear">
				<span id="get-athletic-data" class="btn btn-secondary">Export Data &nbsp;<i class="fa fa-download"></i></span>
			</div>
			
			<div class="clear"></div>
		</div>
		<!-- end #export-filters -->

	</div><!-- end #content-container -->

<?php
	//-- Footer --//
	$this->partial("partials/footer-top");
	$this->partial("partials/scripts/default");
	$this->partial("partials/scripts/athletic-improvement-report");
	$this->partial("partials/scripts/athletic-data-export");
	$this->partial("partials/footer-bottom");