<?php

//-- Page Vars --//
$page_title = 'Assessment Protocols';


	//-- Pull in Header --//
	Phalcon\Tag::appendTitle($page_title);
	$this->partial("partials/header-top");
	$this->partial("partials/styles/athletic-curriculum");
	$this->partial("partials/header-bottom");

	//-- Page Content Title --//
	echo '<div id="content-header"><h1>'.$page_title.'</h1></div><!-- #content-header -->';

	//-- Page Content --// ?>
	<div id="content-container">
		
		<?php $this->flashSession->output(); ?>
		
		<ul>
			<li><a class="ui-lightbox-video" href="/pdf/test-protocols/testing_protocol_20_yard_sprint.pdf">20 Yard Sprint</a></li>
			<li><a class="ui-lightbox-video" href="/pdf/test-protocols/testing_protocol_balance_test.pdf">Balance</a></li>
			<li><a class="ui-lightbox-video" href="/pdf/test-protocols/testing_protocol_BMI.pdf">Body Mass Index (BMI)</a></li>
			<li><a class="ui-lightbox-video" href="/pdf/test-protocols/testing_protocol_hex_agility_test.pdf">Hex Test</a></li>
			<li><a class="ui-lightbox-video" href="/pdf/test-protocols/testing_protocol_pacer_test.pdf">PACER</a></li>
			<li><a class="ui-lightbox-video" href="/pdf/test-protocols/testing_protocol_plank.pdf">Plank</a></li>
			<li><a class="ui-lightbox-video" href="/pdf/test-protocols/testing_protocol_90-degree_push-up.pdf">Push Up</a></li>
			<li><a class="ui-lightbox-video" href="/pdf/test-protocols/testing_protocol_straight_leg_raise_test.pdf">Straight Leg Raise</a></li>
			<li><a class="ui-lightbox-video" href="/pdf/test-protocols/testing_protocol_vertical_jump.pdf">Vertical Jump</a></li>
		</ul>
		
	</div><!-- end #content-container -->

<?php
	//-- Footer --//
	$this->partial("partials/footer-top");
	$this->partial("partials/scripts/athletic");
	$this->partial("partials/footer-bottom");