<?php

date_default_timezone_set('America/Denver');

//-- Page Vars --//
$page_title = 'View Access Logs';


	//-- Pull in Header --//
	Phalcon\Tag::appendTitle($page_title);
	$this->partial("partials/header-top");
	$this->partial("partials/styles/default");
	$this->partial("partials/header-bottom");

	//-- Page Content Title --//
	echo '<div id="content-header"><h1>'.$page_title.'</h1></div><!-- #content-header -->';

	//-- Page Content --// ?>
	<div id="content-container">
		
		<?php $this->flashSession->output(); ?>
		
		<div id="controlBar" class="col-md-12">
			
			<!-- Refresh Button -->
			<div class="btn-group" title="Refresh Page" style="margin-right: 5px;">
				<form id="refresh-page" action="" method="post">
					<span class="btn btn-success" id="refresh-ctrl-btn" onclick="jQuery('#refresh-page').submit();"><i class="fa fa-refresh"></i> <span>Refresh</span></span>
					<?php echo $inputs.$filters; ?>
				</form>
			</div>
			
			<div class="limit-results" title="Display Limit" style="float: right;">
				<form id="changeLimit" action="" method="post">
					<div id="bulk-actions" class="btn-group">
						<button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">
							<span id="limit-display-txt">Display &nbsp;</span><span class="badge badge-tertiary"><?php echo $limit; ?></span> <span class="caret"></span>
						</button>
						<ul class="dropdown-menu" role="menu">
							<?php
								$numRes = array(10, 25, 50, 100);
								foreach($numRes as $num){ ?>
									<li><a href="#" data-val="<?php echo $num; ?>"><?php echo $num; ?></a></li><?php
								}
							?>
						</ul>
						<input type="hidden" name="limit" id="theLimit" class="form-control" value="<?php echo $limit; ?>" />
					</div>
				</form>
			</div><!-- /.limit-results -->

		</div><!-- /#controlBar -->
		
		<div id="display-results" class="col-md-12">
			<div class="table-responsive">
				
				<table class="table table-hover table-bordered">
					<thead>
						<tr>
							<th>
								<form id="form1" action="" method="post">
									<input type="hidden" name="field" value="userid" />
									<span onclick="jQuery('#form1').submit();">User ID</span>
									<?php
									echo $lastField;
									if($field == 'userid'){ echo '<i class="fa fa-sort-'.$dir.'"></i>'; }
									?>
								</form>
							</th>
							<th>
								<form id="form2" action="" method="post">
									<input type="hidden" name="field" value="username" />
									<span onclick="jQuery('#form2').submit();">Username</span>
									<?php
									echo $lastField;
									if($field == 'username'){ echo '<i class="fa fa-sort-'.$dir.'"></i>'; }
									?>
								</form>
							</th>
							<th>
								<form id="form3" action="" method="post">
									<input type="hidden" name="field" value="ip" />
									<span onclick="jQuery('#form3').submit();">IP Address</span>
									<?php
									echo $lastField;
									if($field == 'ip'){ echo '<i class="fa fa-sort-'.$dir.'"></i>'; }
									?>
								</form>
							</th>
							<th class="hideable">
								<form id="form4" action="" method="post">
									<input type="hidden" name="field" value="superpass" />
									<span onclick="jQuery('#form4').submit();">Admin Logged In As User</span>
									<?php
									echo $lastField;
									if($field == 'superpass'){ echo '<i class="fa fa-sort-'.$dir.'"></i>'; }
									?>
								</form>
							</th>
							<th>
								<form id="form5" action="" method="post">
									<input type="hidden" name="field" value="time" />
									<span onclick="jQuery('#form5').submit();">Time</span>
									<?php
									echo $lastField;
									if($field == 'time'){ echo '<i class="fa fa-sort-'.$dir.'"></i>'; }
									?>
								</form>
							</th>
						</tr>
					</thead>
					<tbody>
						<?php
						if(count($loginAttempts) > 0){
							foreach($loginAttempts as $attempt){ ?>
								<tr>
									<td><?php echo $attempt->userid; ?></td>
									<td><?php echo $attempt->username ? $attempt->username : 'N/A'; ?></td>
									<td><?php echo $attempt->ip; ?></td>
									<td class="hideable"><?php echo $attempt->superpass ? 'Yes' : 'No'; ?></td>
									<td><?php echo date('M jS, Y @ h:ia', $attempt->time); ?></td>
								</tr><?php
							}
						}else{ ?>
							<tr><td colspan="5">No Results</td></tr><?php
						} ?>
					</tbody>
				</table>
				
			</div><!-- /.table-responsive -->
		</div><!-- /#display-results -->
		
		<div class="col-md-12">
			
			<?php
			//-- Create Pager --//
			if($totalAttempts > $limit){
				//-- Calculations --//
				$numLimit = $totalAttempts / $limit;
				$curMin = (($pageNum - 1) * $limit) + 1;
				$curMax = $pageNum * $limit;
				if($curMax > $totalAttempts){ $curMax = $totalUsers; }
				
				echo '<div class="users-pager">';
				echo '<span class="page-count">Showing <span class="curMin">'.$curMin.'</span> - <span class="curMax">'.$curMax.'</span> of '.$totalAttempts.' Logins</span>';
				echo '<ul class="pagination" data-limit="'.$limit.'" data-total="'.$totalAttempts.'">';
				if($pageNum == 1){ $prevClass = 'disabled'; }else{ $prevClass = ''; }
				echo '<li class="prev '.$prevClass.'"><a href="#">← Previous</a></li>';
				$i = 0;
				while($i < $numLimit){
					$i++;
					if($i == $pageNum){ $theClass = 'active '; }else{ $theClass = ''; }
					if($i == 1){ $theClass.= 'firstPage '; }
					if($i >= $numLimit){ $theClass.= 'lastPage '; }
					if(!$theClass && $numLimit > 5 && ($i > ($pageNum + 2) || $i < ($pageNum - 2))){ $theClass.= 'scrunch '; }
					echo '<li class="'.$theClass.'"><a href="#" data-page="'.$i.'">'.$i.'</a></li>';
				}
				if($curMax == $totalUsers){ $nextClass = 'disabled'; }else{ $nextClass = ''; }
				echo '<li class="next '.$nextClass.'"><a href="#">Next → </a></li></ul>';
				echo '</div>'; ?>
				
				<form id="pagerForm" action="" method="post">
					<input type="hidden" name="pageNum" id="pageNumber" value="<?php echo $pageNum; ?>" />
					<?php echo $inputs.$limitFilter; ?>
				</form><?php
			} ?>
			
		</div>
		
	</div><!-- /#content-container -->

<?php
	//-- Footer --//
	$this->partial("partials/footer-top");
	$this->partial("partials/scripts/manage-users");
	$this->partial("partials/footer-bottom");
?>