<?php

//-- PHP Includes --//
include "inc/states.php";

//-- Page Vars --//
$page_title = 'Manage School Years';


	//-- Pull in Header --//
	Phalcon\Tag::appendTitle($page_title);
	$this->partial("partials/header-top");
	$this->partial("partials/styles/default");
	$this->partial("partials/header-bottom");

	//-- Page Content Title --//
	echo '<div id="content-header"><h1>'.$page_title.'</h1></div><!-- #content-header -->';

	//-- Page Content --// ?>
	<div id="content-container">
		
		<?php $this->flashSession->output(); ?>
		
		<div id="semesters-section" class="col-sm-11 col-sm-offset-1">
			<div id="semester-box">
				<h3><i class="fa fa-calendar"></i> School Years</h3>
				<div id="create-new-semester" class="form-group">
					<label for="new-semester">Create New School Year</label><br />
					<input type="text" id="new-semester" class="form-control" value="" placeholder="Enter Name of School Year" />
					<span class="btn btn-primary" id="createSemester">Create</span>
				</div>
				<h4 style="margin: 30px 0 8px;">Set Current School Year</h4>
				<p>Select the current school year to make it active for grading. Below is a list of previous and current school years.<br />This is only to be changed after all grades have been collected for the school year, once the current school year has been changed all future grades will be attributed to the new year.</p>
				<div id="semester-list">
					<?php
					//-- List out all semesters --//
					if(isset($semesters) && $semesters){
						foreach($semesters as $semester){ ?>
							<div class="checkbox">
								<label>
									<?php if($semester->active){ $check = 'checked="checked"'; $addClass = 'active'; }else{ $check = ''; $addClass = ''; } ?>
									<input type="checkbox" class="setSemester <?php echo $addClass; ?>" value="<?php echo $semester->id; ?>" <?php echo $check; ?>>
									<span class="bold semester-name"><?php echo $semester->semesterName; ?></span>
								</label>
								<span class="text-primary editSemester" data-sem-val="<?php echo $semester->id; ?>" title="Rename Semester"><i class="fa fa-pencil"></i></span>
								<span class="text-primary delSemester" data-sem-val="<?php echo $semester->id; ?>" title="Remove Semester"><i class="fa fa-times"></i></span>
							</div><?php
						}
					} ?>
				</div>
			</div>
		</div>
		
	</div><!-- end #content-container -->

<?php
	//-- Footer --//
	$this->partial("partials/footer-top");
	$this->partial("partials/scripts/school-year-management");
	$this->partial("partials/footer-bottom");
?>