<?php

//-- PHP Includes --//
include "inc/states.php";

//-- Page Vars --//
$page_title = 'Setup New School Year';


	//-- Pull in Header --//
	Phalcon\Tag::appendTitle($page_title);
	$this->partial("partials/header-top");
	$this->partial("partials/styles/default");
	$this->partial("partials/header-bottom");

	//-- Page Content Title --//
	echo '<div id="content-header"><h1>'.$page_title.'</h1></div><!-- #content-header -->';

	//-- Page Content --// ?>
	<div id="content-container">
		
		<?php $this->flashSession->output(); ?>
		
		<div class="row">
			<div class="col-xs-12">
				<h3 class="margin-bottom-20"><i class="fa fa-cog"></i> Start New School Year</h3>
				<blockquote>
					<em>To start a new school year in Athlos Tools, we need to clear out the rosters and start with a blank slate.<br />Follow the steps below to make sure you are ready to start your new school year.</em>
				</blockquote>
				
				<div class="row">
					<div class="col-xs-12">
						<div class="panel">
							<div class="panel-heading">
								<h4 class="font-weight-600"><span style="font-weight: bold;">Step #1</span> - Clear rosters from last year and unenroll all students.</h4>
							</div><!-- /.panel-heading -->
							<div class="panel-body">
								<p>For this step, we have made it simple. You just need to click the button below, and then confirm that you for sure want to run this process by confirming this action in the popup that will appear. This may take a little while to complete, so please be patient while the script is running.</p>
								<p><span id="remove-associations" class="btn btn-primary"><i class="fa fa-eraser"></i> &nbsp;Clear Rosters &amp; Unenroll Students</span></p>
							</div><!-- /.panel-body -->
						</div><!-- /.panel -->
					</div><!-- /.col -->
				</div><!-- /.row -->
				
				<div class="row">
					<div class="col-xs-12">
						<div class="panel">
							<div class="panel-heading">
								<h4 class="font-weight-600"><span style="font-weight: bold;">Step #2</span> - Update the current school year to the correct one.</h4>
							</div><!-- /.panel-heading -->
							<div class="panel-body">
								<p>Make sure the year displayed below is the correct term for the new school year. If it is incorrect and needs to be updated, please click the button titled "Change School Year" to open a new window where you can set the select the correct school year.</p>
								<div class="row margin-bottom-0">
									<div class="col-xs-12 col-sm-6">
										<div class="form-group">
											<label>Current School Year:</label>
											<input type="text" id="current-year" class="form-control" value="<?php echo $activeSemester; ?>" readonly="readonly" />
										</div>
										<p><a href="/administration/" target="_blank" class="btn btn-secondary"><i class="fa fa-crosshairs"></i> &nbsp;Change School Year</a></p>
									</div><!-- /.col -->
								</div><!-- /.row -->
							</div><!-- /.panel-body -->
						</div><!-- /.panel -->
					</div><!-- /.col -->
				</div><!-- /.row -->
				
				<div class="row">
					<div class="col-xs-12">
						<div class="panel">
							<div class="panel-heading">
								<h4 class="font-weight-600"><span style="font-weight: bold;">Step #3</span> - Send out reminders to athletic coaches to login and setup their new class rosters.</h4>
							</div><!-- /.panel-heading -->
							<div class="panel-body">
								<p>We realize that once you have cleared out the rosters and have the school year setup, the next step is getting the new rosters created. To help facilitate this, we have added an easy way to email all the campus coaches.</p>
								<p>Simply click the button below titled "Configure Email Options" which will open up a modal window where you can select which schools you would like to email, and which users you would like to email. Once configured, click the "Send Emails" button to initiate sending the email reminder to those users to start setting up their rosters.</p>
								<p><span id="configure-roster-reminder" class="btn btn-tertiary"><i class="fa fa-envelope"></i> &nbsp;Configure Email Options</span></p>
							</div><!-- /.panel-body -->
						</div><!-- /.panel -->
					</div><!-- /.col -->
				</div><!-- /.row -->
				
			</div><!-- /.col -->
		</div><!-- /.row -->
		
	</div><!-- end #content-container -->

<?php
	//-- Footer --//
	$this->partial("partials/footer-top");
	$this->partial("partials/scripts/new-year-setup");
	$this->partial("partials/footer-bottom");
?>