<?php

//-- Page Vars --//
$page_title = 'Performance Character Curriculum';


	//-- Pull in Header --//
	Phalcon\Tag::appendTitle($page_title);
	$this->partial("partials/header-top");
	$this->partial("partials/styles/traits");
	$this->partial("partials/header-bottom");

	//-- Page Content Title --//
	echo '<div id="content-header"><h1>'.$page_title.'</h1></div><!-- #content-header -->';

	//-- Page Content --// ?>
	<div id="content-container">
		
		<?php $this->flashSession->output(); ?>
		
		<?php $this->partial("partials/includes/character-curriculum-content"); ?>
		
	</div><!-- #content-container -->

<?php
	//-- Footer --//
	$this->partial("partials/footer-top");
	$this->partial("partials/scripts/traits");
	$this->partial("partials/footer-bottom");
?>