<?php
/*
*	Widget: Character Curriculum Suggestions Donut Chart
*/

//-- Grab Option --//
$option = Options::findFirst("option = 'character-curriculum-stats'");
$currStats = unserialize($option->value); ?>
<div class="portlet">
	<div class="portlet-header">
		<h3><i class="fa fa-bar-chart-o"></i> Character Curriculum Suggestions</h3>
	</div> <!-- /.portlet-header -->
	<div class="portlet-content">
		<div id="curriculum-donut-chart" class="chart-holder" style="height: 250px"></div>
		<p style="text-align: center; color: #999; margin: 0;">Which schools are adding to PCT curriculum</p>
		<hr style="margin-bottom: 10px;">
		<div class="pull-right">
			<span id="show-detailed-breakdown" class="btn btn-xs btn-link">Show Details</span>
		</div>
		<div id="detailed-breakdown" style="display: none; clear: both;">
			<h5 style="font-weight: 600;">Detailed Breakdown:</h5>
			<ul><?php
				//-- list out suggestion counts --//
				$x = 0;
				$colorArray = array('#e5412d','#f0ad4e','#5cb85c','#3498db','#444444','#888888');
				foreach($currStats as $stat){
					if($stat['label'] != 'Administration'){
						echo '<li>'.$stat['label'].' - <span class="label" style="background-color: '.$colorArray[$x].';">'.$stat['count'].'</span></li>';
					}else{
						echo '<li>'.$stat['label'].' - '.$stat['count'].'</li>';
					}
					$x++;
				} ?>
			</ul>
		</div>
	</div> <!-- /.portlet-content -->
</div> <!-- /.portlet -->