	</div> <!-- /#login-container -->

<?php
	//-- Scripts --//
	echo $this->tag->javascriptInclude("js/canvas-admin/libs/jquery-1.9.1.min.js");
	echo $this->tag->javascriptInclude("js/canvas-admin/libs/jquery-ui-1.9.2.custom.min.js");
	echo $this->tag->javascriptInclude("js/canvas-admin/libs/bootstrap.min.js");
	echo $this->tag->javascriptInclude("js/canvas-admin/plugins/howl/howl.js");
	echo $this->tag->javascriptInclude("js/canvas-admin/App.js");
	echo $this->tag->javascriptInclude("js/canvas-admin/Login.js");	
?>
<script type="text/javascript">
	jQuery(document).ready(function($){
		/*---------------------
			Forgot Password
		----------------------*/
		$('#submitForgot').click(function(e){
			var forgotVal = $('#forgotLogin').val();
			if(forgotVal){
				var ajaxurl = <?php echo '"'.$this->htprotocol.$_SERVER['HTTP_HOST'].'/session/forgot";'."\n"; ?>
				var data = {
					action: "forgot_password",
					forgotVal: forgotVal
					};
				jQuery.post(ajaxurl, data, function(json){
					if(typeof json != 'undefined'){
						var results = jQuery.parseJSON(json);
						if(typeof results.result != 'undefined'){
							if(results.result == 'success'){
								$('#forgotPasswordModal').modal('hide');
								//-- Success - Howler MSG --//
								howlerMsg('success', 'Forgot Password Email Sent', 'The forgot password email was sent successfully to your inbox.', 7500, 'fa fa-check', false);
							}else if(results.result == 'failed'){
								//-- Failed - Howler MSG --//
								howlerMsg('danger', 'Failed to Send Email', 'The email to reset your password failed to send. Submit a support ticket, or contact your school to help resolve the issue.', 7500, 'fa fa-exclamation', false);
							}else if(results.result == 'invalid'){
								//-- Invalid Data - Howler MSG --//
								howlerMsg('danger', 'Could Not Find User', 'Re-enter your username or email address.', 7500, 'fa fa-exclamation', false);
							}
						}
					}
				});
			}
		});
		/*------------------------
			end forgot password
		-------------------------*/	
	});
	
	//-- Error Messages Popup --//
	function howlerMsg(status, title, msg, duration, icon, sticky){
		jQuery.howl ({
			type: status,
			title: title,
			content: msg,
			lifetime: duration,
			iconCls: icon,
			sticky: sticky
		});
	}
</script>

<!-- Forgot Password Modal to display all content -->
<div id="forgotPasswordModal" class="modal fade">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
				<h3 class="modal-title">Forgot Password?</h3>
			</div>
			<div class="modal-body">
				
				<p>
					<span style="font-weight: bold; letter-spacing: 0.3px;">Instructions:</span><br />
					To reset your password, enter your username or email address and click the submit button. An email address will be sent to your inbox with a link to change your password.
				</p>
				
				<div class="form-group">
					<label for="forgotLogin">Username or Email</label><br />
					<input type="text" id="forgotLogin" class="form-control" placeholder="Enter Username or Email Address..." />
					<span class="btn btn-primary" id="submitForgot">Submit</span>
				</div>
				
			</div>
			<div class="modal-footer">
				<button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
			</div>
		</div><!-- /.modal-content -->
	</div><!-- /.modal-dialog -->
</div><!-- /.modal -->

<script>
	//-- Google Analytics Tracking --//
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-48101675-2', 'athlosacademies.org');
  ga('send', 'pageview');
</script>

</body>
</html>