<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js"> <!--<![endif]-->
<head>
	<?php echo Phalcon\Tag::getTitle(); ?>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0" />
	<meta name="description" content="">
	<meta name="author" content="" />
	<link rel="shortcut icon" href="/img/favicon.ico">
    
<?php
	//-- Stylesheets --//
	echo $this->tag->stylesheetLink("https://fonts.googleapis.com/css?family=Open+Sans:400italic,600italic,800italic,400,600,800", false);
	echo $this->tag->stylesheetLink("css/canvas-admin/font-awesome.min.css");
	echo $this->tag->stylesheetLink("css/canvas-admin/bootstrap.min.css");
	echo $this->tag->stylesheetLink("js/canvas-admin/libs/css/ui-lightness/jquery-ui-1.9.2.custom.css");
	echo $this->tag->stylesheetLink("css/canvas-admin/App.css");
	echo $this->tag->stylesheetLink("css/canvas-admin/Login.css");
	echo $this->tag->stylesheetLink("css/canvas-admin/custom.css");
?>	
</head>
<body>
	<div id="login-container">

		<div id="logo">
			<img src="/img/logos/athlos-grading-logo-mark.png" alt="Athlos Academies Logo" />
		</div>