<?php

//-- Page Vars --//
$page_title = 'Secure File Upload';


	//-- Pull in Header --//
	Phalcon\Tag::appendTitle($page_title);
	$this->partial("partials/header-top");
	$this->partial("partials/styles/default");
	$this->partial("partials/header-bottom");

	//-- Page Content Title --//
	echo '<div id="content-header"><h1>'.$page_title.'</h1></div><!-- #content-header -->';

	//-- Page Content --// ?>
	<div id="content-container">
		
		<?php $this->flashSession->output(); ?>
		
		
		<div class="row">
			<?php if($this->session->get("user-role") == 1){ //-- show download tab for admins --// ?>
					<div class="col-md-3 col-sm-5">
						<!-- Stacked Tabs - Navigation -->
						<ul class="nav nav-pills nav-stacked">
							<li class="active">
								<a href="#manage-files" data-toggle="tab"><i class="fa fa-download"></i> &nbsp;&nbsp;Manage Secure Files</a>
							</li>
							<li>
								<a href="#upload-docs" data-toggle="tab"><i class="fa fa-upload"></i> &nbsp;&nbsp;Upload Files</a>
							</li>
						</ul>
					</div><!-- /.col -->
					<div class="col-md-9 col-sm-7">
						<div class="tab-content stacked-content">

							<div class="tab-pane fade in active" id="manage-files">
								<div id="manage-downloads">
									<h3 class="heading"><i class="fa fa-download"></i> Manage Secure Files</h3>
									<?php
										//-- Echo out contents of Amazon Bucket --//
										if(isset($bucket_contents) && $bucket_contents){ ?>
											<div class="row">
												<div class="col-md-12"><?php
													foreach($bucket_contents as $file){
														$fname = $file['name'];
													    $furl = "http://athlos-tools-secure-uploads.s3.amazonaws.com/".$fname;
														$fsize = $file['size'];
														$ext = strtolower(pathinfo($fname, PATHINFO_EXTENSION));

														//-- determine what class to use --//
														if($ext == 'doc' || $ext == 'docx'){
															$useClass = 'download-word';
														}else if($ext == 'zip'){
															$useClass = 'download-zip';
														}else if($ext == 'xls' || $ext == 'xlsx' || $ext == 'csv'){
															$useClass = 'download-xls';
														}else{
															$useClass = 'download-doc';
														}

													    //-- Output link to file --//
														echo '<div class="download '.$useClass.'" style="margin: 0; padding: 18px 0 17px 60px; background-position: 0 10px; background-size: 40px;">';
													    echo '<a href="'.$furl.'">'.$fname.'</a>';
														echo '<span style="margin: 0 0 0 10px; color: #808080;">('.round($fsize / 1024, 1).' KB)</span>';
														echo '<span class="btn btn-xs btn-primary delete-doc" data-name="'.$fname.'" style="margin: 0 0 0 30px;"><i class="fa fa-times"></i> Remove</span>';

														echo '</div>';
													} ?>

												</div> <!-- /.col -->
											</div> <!-- /.row --><?php
										}
									?>
								</div>
							</div><!-- /.tab-pane -->

							<div class="tab-pane fade" id="upload-docs">
			<?php }else{ ?>
					<div class="col-md-12">
			<?php } ?>	
						<div id="upload-documents">
							<h3 class="heading"><i class="fa fa-upload"></i> Send to Web Administrators</h3>

							<p style="margin-bottom: 20px;">
								Select the file that you would like to upload to the secure server. Once uploaded, only web administrators will be able to view your file. Upon successful upload, you should receive a confirmation email.
							</p>

							<div id="form-errors" class="alert alert-danger" style="display: none;"></div>

							<!-- Upload PDF to Amazon Bucket Form -->
							<form id="upload-secure-form" action="" method="post" enctype="multipart/form-data">
								<input type="hidden" name="action" value="upload_resource" />
								<p>
									<span class="btn btn-primary fileinput-button">
							        	<i class="glyphicon glyphicon-plus"></i>
							        	<span>Select Document</span>
							        	<!-- The file input field used as target for the file upload widget -->
							        	<input id="resourceupload" type="file" name="theFile">
							    	</span>
									<span id="document-to-upload">
										<span class="the-doc-name"></span>
									</span>
									<span id="res-up-err" class="alert alert-danger"></span>
								</p>
								<p>
									<label for="add-msg">Add Message / Instructions</label>
									<textarea name="add-msg" id="add-msg" class="form-control" style="margin-bottom: 20px;" rows="" cols=""></textarea>
								</p>
							    <p>
							    	<input type="submit" id="upload-doc" class="btn btn-primary" value="Upload" />
								</p>
							</form>
						</div>
		<?php if($this->session->get("user-role") == 1){ ?>
					</div><!-- /.tab-pane -->
				</div><!-- /.tab-content -->
		<?php } ?>
			</div> <!-- /.col -->
		</div><!-- /.row -->
		
	</div><!-- end #content-container -->

<?php
	//-- Footer --//
	$this->partial("partials/footer-top");
	$this->partial("partials/scripts/secure-upload");
	$this->partial("partials/footer-bottom");
?>