<?php

//-- Page Vars --//
$page_title = 'Movement Breaks';


	//-- Pull in Header --//
	Phalcon\Tag::appendTitle($page_title);
	$this->partial("partials/header-top");
	$this->partial("partials/styles/traits");
	$this->partial("partials/header-bottom");

	//-- Page Content Title --//
	echo '<div id="content-header"><h1>'.$page_title.'</h1></div><!-- #content-header -->';

	//-- Page Content --// ?>
	<div id="content-container">
		
		<?php $this->flashSession->output(); ?>
		
		
		<div class="row">

			<div class="col-md-3 col-sm-4">

			    <ul id="myTab" class="nav nav-pills nav-stacked">

					<?php
					//-- Build Movement Break Types Navigation --//
					foreach($types as $type){ ?>
						<li <?php if($type->id == 1){ echo 'class="active"'; } ?>>
				        	<a href="#<?php echo $type->url_name; ?>-tab" data-toggle="tab" class="<?php echo $type->url_name; ?>">
								<i class="fa <?php echo $type->icon; ?>"></i>
				        		<?php echo '&nbsp;&nbsp;'.$type->type_name; ?>
				        	</a>
				        </li><?php
					} ?>

			    </ul>

			</div> <!-- /.col -->

			<div class="col-md-9 col-sm-8">
				<div class="tab-content stacked-content">
					
					<?php
					
					foreach($types as $type){ ?>
				
						<!-- Movement Breaks Content Section -->
						<div class="tab-pane fade <?php if($type->id == 1){ echo 'in active'; } ?>" id="<?php echo $type->url_name; ?>-tab">
							<h3 class="heading"><?php echo '<i class="fa '.$type->icon.'"></i> &nbsp;'.$type->type_name; ?></h3>
							
							<div id="<?php echo $type->url_name; ?>-content-types" class="tab-content">

								<?php
									//-- Grab posts from movement breaks type --//
									$lessons = MovementBreaks::query()
										->where("post_type = ".$type->id)
										->andWhere("post_status = 'publish'")
										->order("post_title")
										->execute();

									if(!empty($lessons)){
										echo '<div class="result-container">';
										$totalPosts = count($lessons);
										$pageLimit = 6;
										$row = $i = $t = 0;
										foreach($lessons as $post){
											if($t >= $pageLimit){ break; }
											if($i == 0){
												if($row != 0){ echo '</div> <!-- /.row -->'; }
												echo '<div class="row">';
												$row++;
											} ?>
											<div class="col-md-4 col-sm-6" style="max-width: 360px;">

												<?php
												//-- Grab author object --//
												$authorName = 'admin';
												$author = $post->users;

												//-- Determine Layout - based on post properties --//
												if(!empty($post->post_video_url)){
													//-- Video / Image Portlets --// ?>

													<div class="thumbnail">
														<?php
														if(!empty($post->post_video_image)){
															//-- make sure video image is pulling from https --//
															$post->post_video_image = str_ireplace('http://', 'https://', $post->post_video_image);
															if(@getimagesize($post->post_video_image) !== false){
																$post->post_image_url = $post->post_video_image;
															}else{
																$post->post_image_url = '/img/empty-photo_320x180.jpg';
															}
														}else{
															$post->post_image_url = '/img/empty-photo_320x180.jpg';
														}
														
														//-- Set lightbox Url && Classes --//
														if(!empty($post->post_video_url)){
															$post->url = $post->post_video_url;
															$lightboxClass = 'ui-lightbox-video';
														}else if(isset($post->post_image_url)){
															$post->url = $post->post_image_url;
															$lightboxClass = 'ui-lightbox';
														}

														?>
														<div class="thumbnail-view">
															<a href="<?php echo $post->url; ?>" class="thumbnail-view-hover <?php echo $lightboxClass; ?>"></a>
																<img src="<?php echo $post->post_image_url; ?>" style="width: 100%" alt="Gallery Image" />
													    </div>
													    <div class="caption">
															<h3 class="curr-display-head"><?php echo stripslashes(html_entity_decode($post->post_title, ENT_QUOTES)); ?></h3>
															<div class="curr-display-content">
																<?php //-- Truncate visible chars in content to specified amount --//
																$currContent = stripslashes(html_entity_decode($post->post_content, ENT_QUOTES));
																//-- Display Content --//
																echo strip_tags($currContent, '<p><a><b><em><i><ul><blockquote><span><u><li><ol><br>'); ?>
															</div>
															<p class="curr-display-actions">
																<a href="javascript:;" class="btn btn-primary btn-sm btn-sm viewComplex">View</a>
																<?php
																//-- include button for external link if there is one --//
																if($post->post_external_url){ ?>
																	<a href="<?php echo $post->post_external_url; ?>" target="_blank" class="btn btn-secondary btn-sm btn-sm">Resource</a>
																<?php }else if($post->post_video_url){ ?>
																	<a href="<?php echo $post->post_video_url; ?>" target="_blank" class="btn btn-secondary btn-sm btn-sm">Video</a>
																<?php } ?>
															</p>
													    </div>
													    <div class="thumbnail-footer">
													    	<div class="pull-left">
													        	<a class="post-author"><i class="fa fa-user"></i>
																	&nbsp;<?php if(isset($author->usernm) && $author->usernm){ echo $author->usernm; }else{ echo $authorName; } ?>
																</a>
													        </div>

													        <div class="pull-right">
													        	<a class="post-time"><i class="fa fa-clock-o"></i> <?php echo date('M j, Y', $post->post_time); ?></a>
															</div>
														</div>
													</div>

													<?php
												}else{
													//-- Plain Portlets --// ?>
													<div class="portlet portlet-plain">
														<div class="portlet-header">
															<h3><?php echo stripslashes(html_entity_decode($post->post_title, ENT_QUOTES)); ?></h3>
														</div> <!-- /.portlet-header -->
														<div class="portlet-content">

															<div class="curr-display-content">
																<?php //-- Truncate visible chars in content to specified amount --//
																$currContent = stripslashes(html_entity_decode($post->post_content, ENT_QUOTES));
																//-- Display Content --//
																echo str_ireplace('Description', '', strip_tags($currContent, '<p><a><b><em><i><blockquote><span><u><br>')); ?>
															</div>
															<div class="curr-modal-content">
																<?php //-- Truncate visible chars in content to specified amount --//
																$currContent = stripslashes(html_entity_decode($post->post_content, ENT_QUOTES));
																//-- Display Content --//
																echo strip_tags($currContent, '<p><a><b><em><i><ul><blockquote><span><u><li><ol><h1><h2><br>'); ?>
															</div>
															<p class="curr-display-actions">
																<a class="btn btn-primary btn-sm btn-sm viewPlain">View</a>
																<?php
																//-- include button for external link if there is one --//
																if($post->post_external_url){ ?>
																	<a href="<?php echo $post->post_external_url; ?>" target="_blank" class="btn btn-secondary btn-sm btn-sm">Resource</a>
																<?php } ?>
															</p>

															<div class="thumbnail-footer">
														    	<div class="pull-left">
														        	<a class="post-author"><i class="fa fa-user"></i>
																		&nbsp;<?php if(isset($author->usernm) && $author->usernm){ echo $author->usernm; }else{ echo $authorName; } ?>
																	</a>
														        </div>

														        <div class="pull-right">
														        	<a class="post-time"><i class="fa fa-clock-o"></i> <?php echo date('M j, Y', $post->post_time); ?></a>
																</div>
															</div>
														</div> <!-- /.portlet-content -->

													</div> <!-- /.portlet --><?php
												} ?>

											</div> <!-- /.col -->
											<?php
											$i++; $t++; if($i == 3){ $i = 0; }
										}
										//-- add closing div if posts were returned --//
										if(count($lessons) > 0){ echo '</div>'; }
										echo '</div><!-- /.result-container -->';

										//-- Create Pager --//
										if($totalPosts > $pageLimit){
											$numLimit = $totalPosts / $pageLimit;
											echo '<div class="curriculum-pager">';
											echo '<span class="page-count">Showing <span class="curMin">1</span> - <span class="curMax">6</span> of '.$totalPosts.' entries</span>';
											echo '<ul class="pagination" data-limit="'.$pageLimit.'" data-type="'.$type->id.'" data-total="'.$totalPosts.'">';
											echo '<li class="prev disabled"><a href="#">← Previous</a></li>';
											$i = 0;
											while($i < $numLimit){
												$i++;
												if($i == 1){ $theClass = 'active firstPage '; }else{ $theClass = ''; }
												if($i >= $numLimit){ $theClass.= 'lastPage'; }
												if(!$theClass && $numLimit > 5 && $i > 3){ $theClass.= 'scrunch'; }
												echo '<li class="'.$theClass.'"><a href="#" data-page="'.$i.'">'.$i.'</a></li>';
											}
											echo '<li class="next"><a href="#">Next → </a></li></ul>';
											echo '</div>';
										}

									}
								?>

							</div><!-- /.tab-content -->

						</div><!-- /.tab-pane --><?php
						
					} ?>

				</div><!-- /.stacked-content -->

			</div> <!-- /.col -->

		</div> <!-- /.row -->
		
		
		
	</div><!-- #content-container -->

<?php
	//-- Footer --//
	$this->partial("partials/footer-top");
	$this->partial("partials/scripts/breaks");
	$this->partial("partials/footer-bottom");
?>