<?php

//-- Page Vars --//
$page_title = 'Movement Breaks: Contributions';

if(!isset($errFound)){
	$errFound = false;
}


	//-- Pull in Header --//
	Phalcon\Tag::appendTitle($page_title);
	$this->partial("partials/header-top");
	$this->partial("partials/styles/suggestions");
	$this->partial("partials/header-bottom");

	//-- Page Content Title --//
	echo '<div id="content-header"><h1>'.$page_title.'</h1></div><!-- #content-header -->';

	//-- Page Content --// ?>
	<div id="content-container">
		
		<?php $this->flashSession->output(); ?>
		
		<?php //-- use with Debug --//
		// echo $this->getContent(); ?>
		
		<div class="row">
			<div class="col-md-3 col-sm-5">

			    <ul id="myTab" class="nav nav-pills nav-stacked">
					<li <?php if(!$errFound){ echo 'class="active"'; } ?>>
						<a href="#past-suggestions" data-toggle="tab"><i class="fa fa-reorder"></i> &nbsp;&nbsp;Past Contributions</a>
					</li>
			        <li <?php if($errFound){ echo 'class="active"'; } ?>>
						<a href="#suggestion-form" data-toggle="tab"><i class="fa fa-star"></i> &nbsp;&nbsp;Make a Contribution</a>
					</li>
					<li>
						<a href="#report-issue" data-toggle="tab"><i class="fa fa-bug"></i> &nbsp;&nbsp;Report an Issue</a>
					</li>    
			    </ul>
				
			</div> <!-- /.col -->
			
			<div class="col-md-9 col-sm-7">
				<div id="myTabContent" class="tab-content stacked-content">
					<div class="tab-pane fade <?php if($errFound){ echo 'in active'; } ?>" id="suggestion-form">
						
						<h2>Make a Contribution</h2>
						
						<!-- Suggestion Form -->
						<form id="suggestionForm" class="parsley-form" action="/breaks/suggestions" method="post">
							<input type="hidden" name="form-action" value="submit-suggestion">
							<input type="hidden" name="post_author" value="<?php echo $this->session->get("user-id"); ?>">
							
							<div class="form-group">
								<label for="post-title">Title</label>
								<input type="text" name="post_title" id="post-title" class="form-control" value="<?php if($errFound){ echo $this->request->getPost("post_title"); } ?>" data-required="true">
							</div>
							<div class="form-group">	
								<label for="select-input">Content Type</label>
								<select id="post-type" name="content_type" class="form-control" data-required="true">
									<option value="">Select One...</option>
									<?php
									foreach($types as $type){
										$sel = '';
										if($errFound){ if($this->request->getPost("content_type") == $type->id){ $sel = 'selected="selected"'; } }
										echo '<option '.$sel.' value="'.$type->id.'">'.$type->type_name.'</option>';
									}
									?>
								</select>
							</div>
							<div class="form-group" <?php if(!$errFound || $this->request->getPost("content_type") != 2){ echo 'style="display: none;"'; } ?>>
								<label for="post-video">Video Url</label>
								<input type="text" name="post_video" id="post-video" class="form-control" placeholder="http://" value="<?php if($errFound && $this->request->getPost("content_type") == 2 && $this->request->getPost("post_video")){ echo $this->request->getPost("post_video"); } ?>" maxlength="255" <?php if($errFound && $this->request->getPost("content_type") == 2){ echo 'data-required="true"'; } ?>>
							</div>
							<div class="form-group">
								<label for="post-content">Content</label>
								<textarea name="post_content" id="post-content" cols="10" rows="5" class="form-control" placeholder="Enter text ..." data-required="true"><?php if($errFound){ echo $this->request->getPost("post_content"); } ?></textarea>
							</div>
							<div class="form-group">
								<input type="submit" id="submit-suggestion" class="btn btn-primary" value="Submit Contribution">
							</div>
							
							<h4>Additional Options</h4>
							<div class="well">
								<div class="form-group" style="margin-bottom: 5px;">
									<label class="checkbox-inline">
										<input type="checkbox" id="useExternal" name="useExternal" onclick="hideFieldGroup(this, '#post-resource');" <?php if($errFound && $this->request->getPost("post_resource")){ echo 'checked="checked"'; } ?>> Add Link to External Resource
									</label>
									<!--<label class="checkbox-inline">
										<input type="checkbox" id="useImage" name="useImage" onclick="hideFieldGroup(this, '#post-image');" <?php if($errFound && $this->request->getPost("post_image")){ echo 'checked="checked"'; } ?>> Add Featured Image
									</label>-->
								</div>
								<div class="form-group" <?php if(!$errFound || !$this->request->getPost("post_resource")){ echo 'style="display: none;"'; } ?>>
									<label for="post-resource">External Resource Url</label>
									<input type="text" name="post_resource" id="post-resource" class="form-control" placeholder="http://" value="<?php if($errFound && $this->request->getPost("post_resource")){ echo $this->request->getPost("post_resource"); } ?>" maxlength="255">
								</div>
								<!--<div class="form-group" <?php if(!$errFound || !$this->request->getPost("post_image")){ echo 'style="display: none;"'; } ?>>
									<label for="post-image">Featured Image Url</label>
									<input type="text" name="post_image" id="post-image" class="form-control" placeholder="http://" value="<?php if($errFound && $this->request->getPost("post_image")){ echo $this->request->getPost("post_image"); } ?>" maxlength="255">
								</div>-->
							</div>
							
						</form>
						
					</div><!-- /.tab-pane -->
					<div class="tab-pane fade <?php if(!$errFound){ echo 'in active'; } ?>" id="past-suggestions">
						
						<h2>Past Contributions</h2>
						
						<?php
							if($cap['movement-breaks']['manage']){
								//-- Show For Admins --// ?>
								<ul id="tab-sugg-nav" class="nav nav-tabs">
									<li class="active">
										<a href="#pending-posts" data-toggle="tab">Pending</a>
									</li>
									<li>
										<a href="#approved-posts" data-toggle="tab">Approved</a>
									</li>
									<li>
										<a href="#trashed-posts" data-toggle="tab">Trash</a>
									</li>
								</ul>
								<div id="tabbed-suggestions" class="tab-content">
									<div class="tab-pane fade in active" id="pending-posts">
										
										<!-- Pending Approval -->
										<div class="table-responsive">

											<table id="pending-curriculum"
												class="table table-striped table-bordered table-hover table-highlight table-checkable" 
												data-provide="datatable" 
												data-display-rows="8"
												data-info="true"
												data-search="true"
												data-length-change="true"
												data-paginate="true"
											>
												<thead>
													<tr>
														<th></th>
														<th data-filterable="true" data-sortable="true" data-direction="asc">Title</th>
														<th data-filterable="true" data-sortable="true">Type</th>
														<th style="min-width: 170px;">Actions</th>
													</tr>
												</thead>
												<tbody>
													
													<?php
														//-- List out Pending Posts --//
														if($pendingPosts){
															foreach($pendingPosts as $post){ ?>
																<tr>
																	<td><span id="pend-<?php echo $post->id; ?>" class="label label-secondary"><i class="fa fa-clock-o"></i></span></td>
																	<td><?php echo stripslashes(html_entity_decode($post->post_title, ENT_QUOTES)); ?></td>
																	<td><?php echo $types[$post->post_type-1]->type_name; ?></td>
																	<td style="min-width: 170px;">
																		<span class="label label-success approvePost" data-post-val="<?php echo $post->id; ?>" data-status="pend" data-reply="true"><i class="fa fa-check"></i> Approve</span>
																		<span class="label label-primary editPost" data-post-val="<?php echo $post->id; ?>" data-status="pend"><i class="fa fa-pencil"></i> Edit</span>
																		<span class="label label-secondary viewPost" data-post-val="<?php echo $post->id; ?>" data-status="pend"><i class="fa fa-file-text-o"></i> View</span>
																		<span class="label label-tertiary trashPost" data-post-val="<?php echo $post->id; ?>" data-status="pend" data-reason="true"><i class="fa fa-trash-o"></i> Trash</span>
																	</td>
																</tr><?php
															}
														}
													?>
													
												</tbody>
											</table>
										</div> <!-- /.table-responsive -->
										
									</div><!-- /.tab-pane -->
									<div class="tab-pane fade" id="approved-posts">
										
										<!-- Approved Posts -->
										<div class="table-responsive">

											<table id="approved-curriculum" 
												class="table table-striped table-bordered table-hover table-highlight table-checkable" 
												data-provide="datatable" 
												data-display-rows="8"
												data-info="true"
												data-search="true"
												data-length-change="true"
												data-paginate="true"
											>
												<thead>
													<tr>
														<th></th>
														<th data-filterable="true" data-sortable="true" data-direction="asc">Title</th>
														<th data-filterable="true" data-sortable="true">Type</th>
														<th style="min-width: 170px;">Actions</th>
													</tr>
												</thead>
												<tbody>
													
													<?php
														//-- List out Approved Posts --//
														if($approvedPosts){
															foreach($approvedPosts as $post){ ?>
																<tr>
																	<td><span id="approved-<?php echo $post->id; ?>" class="label label-success"><i class="fa fa-check"></i></span></td>
																	<td><?php echo stripslashes(html_entity_decode($post->post_title, ENT_QUOTES)); ?></td>
																	<td><?php echo $types[$post->post_type-1]->type_name; ?></td>
																	<td style="min-width: 170px;">
																		<span class="label label-primary editPost" data-post-val="<?php echo $post->id; ?>" data-status="approved"><i class="fa fa-pencil"></i> Edit</span>
																		<span class="label label-secondary viewPost" data-post-val="<?php echo $post->id; ?>" data-status="approved"><i class="fa fa-file-text-o"></i> View</span>
																		<span class="label label-tertiary trashPost" data-post-val="<?php echo $post->id; ?>" data-status="approved" data-reason="false"><i class="fa fa-trash-o"></i> Trash</span>
																	</td>
																</tr><?php
															}
														}
													?>
													
												</tbody>
											</table>
										</div> <!-- /.table-responsive -->
										
									</div><!-- /.tab-pane -->
									<div class="tab-pane fade" id="trashed-posts">
										
										<!-- Trashed Posts -->
										<div class="table-responsive">

											<table id="trashed-curriculum" 
												class="table table-striped table-bordered table-hover table-highlight table-checkable" 
												data-provide="datatable" 
												data-display-rows="8"
												data-info="true"
												data-search="true"
												data-length-change="true"
												data-paginate="true"
											>
												<thead>
													<tr>
														<th></th>
														<th data-filterable="true" data-sortable="true" data-direction="asc">Title</th>
														<th data-filterable="true" data-sortable="true">Type</th>
														<th style="min-width: 140px;">Actions</th>
													</tr>
												</thead>
												<tbody>
													
													<?php
														//-- List out Trashed Posts --//
														if($trashedPosts){
															foreach($trashedPosts as $post){ ?>
																<tr>
																	<td><span id="trashed-<?php echo $post->id; ?>" class="label label-tertiary"><i class="fa fa-exclamation"></i></span></td>
																	<td><?php echo stripslashes(html_entity_decode($post->post_title, ENT_QUOTES)); ?></td>
																	<td><?php echo $types[$post->post_type-1]->type_name; ?></td>
																	<td style="min-width: 140px;">
																		<span class="label label-success approvePost" data-post-val="<?php echo $post->id; ?>" data-status="trashed"><i class="fa fa-check"></i> Restore</span>
																		<span class="label label-primary deletePost" data-post-val="<?php echo $post->id; ?>" data-status="trashed"><i class="fa fa-ban"></i> Delete</span>
																	</td>
																</tr><?php
															}
														}
													?>
													
												</tbody>
											</table>
										</div> <!-- /.table-responsive -->
										
									</div><!-- /.tab-pane -->
								</div> <!-- / #tabbed-suggestions --> <?php
							}else if($cap['movement-breaks']['submit-contribution']){
								//-- Show for Coaches --// ?>
									<div class="table-responsive">

										<table 
											class="table table-striped table-bordered table-hover table-highlight table-checkable" 
											data-provide="datatable" 
											data-display-rows="8"
											data-info="true"
											data-search="true"
											data-length-change="true"
											data-paginate="true"
										>
											<thead>
												<tr>
													<th data-filterable="true" data-sortable="true" data-direction="asc">Status</th>
													<th data-filterable="true" data-sortable="true" data-direction="asc">Title</th>
													<th data-filterable="true" data-sortable="true">Type</th>
												</tr>
											</thead>
											<tbody>
												
												<?php
													//-- List out My Post Suggestions --//
													if($myPosts){
														foreach($myPosts as $post){ ?>
															<tr>
																<td>
																	<?php if($post->post_status == 'publish'){ ?>
																		<span class="label label-success"><i class="fa fa-check"></i> Approved</span>
																	<?php }else if($post->post_status == 'draft'){ ?>
																		<span class="label label-secondary"><i class="fa fa-clock-o"></i> Pending</span>
																	<?php }else if($post->post_status == 'trash'){ ?>
																		<span class="label label-tertiary"><i class="fa fa-ban"></i> Declined</span>
																	<?php } ?>
																</td>
																<td><?php echo stripslashes(html_entity_decode($post->post_title, ENT_QUOTES)); ?></td>
																<td><?php echo $types[$post->post_type-1]->type_name; ?></td>
															</tr><?php
														}
													}
												?>
												
											</tbody>
										</table>
									</div> <!-- /.table-responsive --> <?php
							}
						?>
						
					</div><!-- /.tab-pane -->
					
					<div class="tab-pane fade" id="report-issue">
						
						<h2>Report Issue With Movement Breaks</h2>
						
						<!-- Suggestion Form -->
						<form id="issueForm" class="parsley-form" action="/breaks/report" method="post">
							<input type="hidden" name="form-action" value="submit-bug">
							
							<div class="form-group">
								<label for="issue-subject">What's the problem?</label>
								<input type="text" name="issue_subject" id="issue-subject" class="form-control" value="" data-required="true" maxlength="80">
							</div>
							
							<div class="form-group">
								<label for="issue-content">Details</label>
								<textarea name="issue_content" id="issue-content" cols="10" rows="5" class="form-control" placeholder="Enter text ..." data-required="true"><?php if($errFound){ echo $this->request->getPost("post_content"); } ?></textarea>
							</div>
							<div class="form-group">
								<input type="submit" id="submit-issue" class="btn btn-primary" value="Submit Issue">
							</div>
							
						</form>
						
					</div><!-- /.tab-pane -->
					
				</div><!-- /#myTabContent -->
			</div> <!-- /.col -->
		</div><!-- /.row -->
		
	</div><!-- #content-container -->

<?php
	//-- Footer --//
	$this->partial("partials/footer-top");
	$this->partial("partials/scripts/movement-break-suggestions");
	$this->partial("partials/footer-bottom");
?>