<?php

	//-- Scripts --//
	echo $this->tag->javascriptInclude("js/canvas-admin/libs/jquery-1.9.1.min.js");
	echo $this->tag->javascriptInclude("js/canvas-admin/libs/jquery-ui-1.9.2.custom.min.js");
	echo $this->tag->javascriptInclude("js/canvas-admin/libs/bootstrap.min.js");
	echo $this->tag->javascriptInclude("js/canvas-admin/plugins/howl/howl.js");
	echo $this->tag->javascriptInclude("js/bootbox.min.js");
	echo $this->tag->javascriptInclude("js/canvas-admin/plugins/parsley/parsley.js");
	echo $this->tag->javascriptInclude("js/canvas-admin/plugins/magnific/jquery.magnific-popup.min.js");
	echo $this->tag->javascriptInclude("js/canvas-admin/App.js");
	echo $this->tag->javascriptInclude("js/canvas-admin/libs/raphael-2.1.2.min.js");
	
?>
<script type="text/javascript">
	jQuery(document).ready(function($){
		/*--------------------------
			Resource Upload Form
		---------------------------*/
		$('#upload-secure-form').submit(function(){
			$('#form-errors').hide();
			var doc_url = $('#resourceupload').val();
			if(doc_url){
				var ext = doc_url.substr(doc_url.lastIndexOf('.') + 1).toLowerCase();
				if(ext == 'pdf' || ext == 'doc' || ext == 'docx' || ext == 'zip' || ext == 'xls' || ext == 'xlsx' || ext == 'csv'){
					//-- Successful upload --//
				}else{
					//-- if invalid filetype --//
					$('#form-errors').html('<strong>Wrong Filetype!</strong> <span>Only PDF, Word Docs & Spreadsheets are Allowed.</span>').show();
					return false;
				}
			}else{
				//-- no file selected --//
				$('#form-errors').html('<strong>No File Selected!</strong> <span>Select a file and then try again.</span>').show();
				return false;
			}
		});
		
		$('#resourceupload').change(function(){
			var doc_url = $(this).val();
			var doc_name = doc_url.substr(doc_url.lastIndexOf('\\') + 1);
			var ext = doc_name.substr(doc_name.lastIndexOf('.') + 1).toLowerCase();
			//-- make sure document is selected --//
			if(doc_url){
				//-- Make sure is valid filetype --//
				if(ext == 'pdf' || ext == 'doc' || ext == 'docx' || ext == 'zip' || ext == 'xls' || ext == 'xlsx' || ext == 'csv'){
					//-- mark with right filetype class --//
					$('#document-to-upload').removeAttr('class');
					$('#document-to-upload').addClass(ext);
					
					$('#document-to-upload .the-doc-name').text(doc_name);
					$('#res-up-err').hide();
					$('#document-to-upload').show();
				}else{
					$('#document-to-upload').hide();
					$('#res-up-err').html('<strong>Wrong Filetype!</strong> <span>PDF, Word Docs & Spreadsheets are Allowed.</span>').show();
					$('#document-to-upload .the-doc-name').text('');
				}
			}else{
				$('#document-to-upload').hide();
				$('#res-up-err').html('<strong>Oh Snap!</strong> <span>No document selected.</span>').show();
				$('#document-to-upload .the-doc-name').text('');
			}
		});
		/*-- end resource upload form --*/
		
		/*-------------------------------------
			Delete Resource from S3 Storage
		--------------------------------------*/
		$('.delete-doc').click(function(){
			var filename = $(this).attr('data-name');
			var container = $(this).parent('div.download');
			bootbox.confirm("Are you sure you want to delete <strong>"+ filename +"</strong>?", function(result) {
				if(result){
					var ajaxurl = <?php echo '"'.$this->htprotocol.$_SERVER['HTTP_HOST'].'/index/deletefile";'."\n"; ?>
					var data = {
						action: "delete_file",
						filename: filename
						};
					jQuery.post(ajaxurl, data, function(json){
						if(typeof json != 'undefined'){
							var results = jQuery.parseJSON(json);
							if(typeof results.result != 'undefined'){
								if(results.result == 'success'){
									//-- Hide document on page --//
									container.delay(500).slideUp('fast');

									//-- Success - Howler MSG --//
									howlerMsg('success', 'Document Deleted', 'The document was removed successfully.', 7500, 'fa fa-check', false);
								}else if(results.result == 'failed'){
									//-- Failed - Howler MSG --//
									howlerMsg('danger', 'Document Not Removed', 'There was a problem removing the document, Please refresh the page and try again.', 7500, 'fa fa-ban', false);
								}
							}
						}
					});
				}
			});
		});
		/*-- end delete resource --*/
	});
</script>