<?php

//-- PHP Includes --//
include "inc/states.php";

//-- Page Vars --//
$page_title = 'Tutorials';


	//-- Pull in Header --//
	Phalcon\Tag::appendTitle($page_title);
	$this->partial("partials/header-top");
	$this->partial("partials/styles/default");
	$this->partial("partials/header-bottom");

	//-- Page Content Title --//
	echo '<div id="content-header"><h1>'.$page_title.'</h1></div><!-- #content-header -->';

	//-- Page Content --// ?>
	<div id="content-container">
		
		<?php $this->flashSession->output(); ?>
		
		<h3>Grading For Parents</h3>
		<iframe src="https://player.vimeo.com/video/111650763" width="500" height="281" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>
	
	<?php //-- Hide Teacher Tut for Parents /Students --//
	if($this->session->get("user-role") < 5){ ?>
		<hr>
		<h3>Grading For Teachers</h3>
		<iframe src="https://player.vimeo.com/video/94595074" width="500" height="281" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>
	<?php } ?>
		
	</div>

<?php
	//-- Footer --//
	$this->partial("partials/footer-top");
	$this->partial("partials/scripts/default");
	$this->partial("partials/footer-bottom");
?>