<?php

//-- Page Vars --//
$page_title = 'Prepared Mind';


	//-- Pull in Header --//
	Phalcon\Tag::appendTitle($page_title);
	$this->partial("partials/header-top");
	$this->partial("partials/styles/athletic-curriculum");
	$this->partial("partials/header-bottom");

	//-- Page Content Title --//
	echo '<div id="content-header"><h1>'.$page_title.'</h1></div><!-- #content-header -->';

	//-- Page Content --// ?>
	<div id="content-container">
		
		<?php $this->flashSession->output(); ?>
		
		<div id="manage-downloads" style="margin: 40px;">
			<?php
				//-- Echo out contents of Amazon Bucket --//
				//-- Level Navigation --//
				if(isset($bucket_contents) && $bucket_contents){ ?>
					<div class="row">
						<div class="col-md-3 col-sm-4">

						    <ul id="myTab" class="nav nav-pills nav-stacked">
								<?php
								$pillCount = 1;
								foreach($bucket_contents as $unit_key => $unit_contents){ ?>
									<li <?php if($pillCount == 1){ echo 'class="active"'; } ?>>
							        	<a href="#unit-<?php echo $unit_key; ?>-contents" data-toggle="tab">
							        		<i class="fa <?php echo $icon_map[$unit_key]; ?>"></i> 
							        		&nbsp;&nbsp;<?php echo ucwords(str_ireplace('-', ' ', $unit_key)); ?>
							        	</a>
							        </li><?php
									$pillCount++;
								} ?>
						    </ul>
							
						</div> <!-- /.col -->
						
						<div class="col-md-9 col-sm-8">
						      <div class="tab-content stacked-content">

								<?php
								//-- Lesson Navigation --//
								$panelCount = 1;
								foreach($bucket_contents as $unit_key => $unit_contents){ ?>
									<div class="tab-pane fade <?php if($panelCount == 1){ echo 'in active'; } ?>" id="unit-<?php echo $unit_key; ?>-contents">
										
										<div class="col-md-12">
										    <h3><?php echo '<i class="fa '.$icon_map[$unit_key].'"></i> &nbsp;'.ucwords(str_ireplace('-', ' ', $unit_key)); ?></h3>
											
											<label for="innerTabs-<?php echo $unit_key; ?>">Curricular Units</label><br />
											<select id="innerTabs-<?php echo $unit_key; ?>" class="lesson-nav form-control">
												<option value="">Select Grade Level</option><?php
													foreach($unit_contents as $folder => $folder_contents){ ?>
														<option value="#folder-grade-<?php echo $folder; ?>"><?php echo $folder_contents[0]; ?></option><?php
													} ?>
											</select>
											
											<div id="unit-<?php echo $unit_key; ?>-tab-nav" class="tab-content" style="margin: 15px 0 0; padding: 20px 0 0; border-top: 1px dashed #eaeaea;"><?php
												//-- List out lessons by topic --//
												$num = 0;
												foreach($unit_contents as $folder => $folder_contents){ ?>
													<div class="tab-pane fade" id="folder-grade-<?php echo $folder; ?>">
														<h4 style="padding-bottom: 8px; border-bottom: 2px solid #e1e1e1;"><?php echo $folder_contents[0]; ?></h4><?php
														foreach($folder_contents[1] as $file){
														    $fname = $file['name'];
														    $furl = "http://athlos-tools-prepared-minds-".$unit_key."-grade-".$folder.".s3.amazonaws.com/".$fname;
															$fsize = $file['size'];
															$ext = strtolower(pathinfo($fname, PATHINFO_EXTENSION));

															//-- determine what class to use --//
															if($ext == 'doc' || $ext == 'docx'){
																$useClass = 'download-word';
															}else if($ext == 'zip'){
																$useClass = 'download-zip';
															}else if($ext == 'xls' || $ext == 'xlsx'){
																$useClass = 'download-xls';
															}else{
																$useClass = 'download-doc';
															}

														    //-- Output link to file --//
															echo '<div class="'.$useClass.'" style="margin: 0; padding: 18px 0 17px 60px; background-position: 0 10px; background-size: 40px;">';
														    echo '<a href="'.$furl.'">'.$fname.'</a>';
															echo '<span style="margin: 0 0 0 10px; color: #808080;">('.round($fsize / 1024, 1).' KB)</span>';
															echo '<span onclick="location.href = \''.$furl.'\'" class="btn btn-xs btn-primary" style="margin: 0 0 0 30px;"><i class="fa fa-download"></i> &nbsp;Download</span>';
															echo '</div>';
														} ?>
														
													</div> <!-- /.tab-pane --><?php
													$num++;
												} ?>
											</div> <!-- /.tab-content -->
										</div> <!-- /.col -->
										
									</div> <!-- /.tab-pane --><?php
									$panelCount++;
								} ?>
									
						      </div> <!-- /.stacked-content -->

						</div> <!-- /.col -->
					</div> <!-- /.row --><?php	
				} ?>
		</div>
		
	</div><!-- end #content-container -->

<?php
	//-- Footer --//
	$this->partial("partials/footer-top");
	$this->partial("partials/scripts/prepared-minds");
	$this->partial("partials/footer-bottom");
?>