<?php

//-- Page Vars --//
$page_title = 'Prepared Minds Index Page';


	//-- Pull in Header --//
	Phalcon\Tag::appendTitle($page_title);
	$this->partial("partials/header-top");
	$this->partial("partials/styles/athletic-curriculum");
	$this->partial("partials/header-bottom");

	//-- Page Content Title --//
	echo '<div id="content-header"><h1>'.$page_title.'</h1></div><!-- #content-header -->';

	//-- Page Content --// ?>
	<div id="content-container">
		
		<?php $this->flashSession->output(); ?>
		
		<div id="manage-downloads" style="margin: 40px;">
			<?php
			//-- List out all folders in S3 storage --//
			/*if(isset($bList) && $bList){
				echo count($bList);
				foreach($bList as $bli){
					print_r($bli);
					echo '<br />';
				}
				echo '<br /><br />';
			}*/
			?>
		</div>
		
	</div><!-- end #content-container -->

<?php
	//-- Footer --//
	$this->partial("partials/footer-top");
	$this->partial("partials/scripts/athletic");
	$this->partial("partials/footer-bottom");