<?php

//-- Page Vars --//
$page_title = 'Downloads';


	//-- Pull in Header --//
	Phalcon\Tag::appendTitle($page_title);
	$this->partial("partials/header-top");
	$this->partial("partials/styles/default");
	$this->partial("partials/header-bottom");

	//-- Page Content Title --//
	echo '<div id="content-header"><h1>'.$page_title.'</h1></div><!-- #content-header -->';

	//-- Page Content --// ?>
	<div id="content-container">
		
		<?php $this->flashSession->output(); ?>
		
		<div id="manage-downloads" style="margin: 40px;">
			<?php
				//-- Echo out contents of Amazon Bucket --//
				if(isset($bucket_contents) && $bucket_contents){
					foreach($bucket_contents as $file){
					    $fname = $file['name'];
					    $furl = "http://athlos-tools-resources.s3.amazonaws.com/".$fname;
						$fsize = $file['size'];
						$ext = strtolower(pathinfo($fname, PATHINFO_EXTENSION));
						
						//-- determine what class to use --//
						if($ext == 'doc' || $ext == 'docx'){
							$useClass = 'download-word';
						}else{
							$useClass = 'download-doc';
						}
						
					    //-- Output link to file --//
						echo '<div class="'.$useClass.'">';
					    echo '<a href="'.$furl.'">'.$fname.'</a>';
						echo '<span style="margin: 0 0 0 10px; color: #808080;">('.round($fsize / 1024, 1).' KB)</span>';
						echo '<span onclick="location.href = \''.$furl.'\'" class="btn btn-xs btn-primary" style="margin: 0 0 0 30px;"><i class="fa fa-download"></i> &nbsp;Download</span>';
						echo '</div>';
					}
				}
			?>
		</div>
		
	</div><!-- end #content-container -->

<?php
	//-- Footer --//
	$this->partial("partials/footer-top");
	$this->partial("partials/scripts/default");
	$this->partial("partials/footer-bottom");