<?php

//-- PHP Includes --//
include "inc/states.php";

//-- Page Vars --//
$page_title = 'Manage Grading';


	//-- Pull in Header --//
	Phalcon\Tag::appendTitle($page_title);
	$this->partial("partials/header-top");
	$this->partial("partials/styles/default");
	$this->partial("partials/header-bottom");

	//-- Page Content Title --//
	echo '<div id="content-header"><h1>'.$page_title.'</h1></div><!-- #content-header -->';

	//-- Page Content --// ?>
	<div id="content-container">
		
		<?php $this->flashSession->output(); ?>
		
		<div class="col-md-3 col-sm-5">
			<!-- Stacked Tabs - Navigation -->
			<ul class="nav nav-pills nav-stacked">
				<?php if($this->session->get("user-role") == 1){ ?>
					<li class="active">
						<a href="#semesters-section" data-toggle="tab"><i class="fa fa-calendar"></i> &nbsp;&nbsp;Semesters</a>
					</li><?php
				} ?>
				<li <?php if($this->session->get("user-role") == 2){ echo 'class="active"'; } ?>>
					<a href="#grade-notifications" data-toggle="tab"><i class="fa fa-envelope"></i> &nbsp;&nbsp;Grading Notifications</a>
				</li>
			</ul>

		</div><!-- /.col -->

		<div class="col-md-9 col-sm-7">

			<div class="tab-content stacked-content">
				<?php //-- SEMESTERS --//
				if($this->session->get("user-role") == 1){ ?>
					<div class="tab-pane fade in active" id="semesters-section">
						<div id="semester-box">
							<h3><i class="fa fa-calendar"></i> Semesters</h3>
							<div id="create-new-semester" class="form-group">
								<label for="new-semester">Create New Semester</label><br />
								<input type="text" id="new-semester" class="form-control" value="" placeholder="Enter Semester Name" />
								<span class="btn btn-primary" id="createSemester">Create</span>
							</div>
							<h4 style="margin: 30px 0 8px;">Set Current Semester</h4>
							<p>Select the current semester to make it active for grading. Below is a list previous and current semesters.<br />This is to only be changed after all grades have been collected, otherwise once the current semester is changed all grades from that point on will be attributed to the new semester.</p>
							<div id="semester-list">
								<?php
								//-- List out all semesters --//
								if(isset($semesters) && $semesters){
									foreach($semesters as $semester){ ?>
										<div class="checkbox">
											<label>
												<?php if($semester->active){ $check = 'checked="checked"'; $addClass = 'active'; }else{ $check = ''; $addClass = ''; } ?>
												<input type="checkbox" class="setSemester <?php echo $addClass; ?>" value="<?php echo $semester->id; ?>" <?php echo $check; ?>>
												<span class="bold semester-name"><?php echo $semester->semesterName; ?></span>
											</label>
											<span class="text-primary editSemester" data-sem-val="<?php echo $semester->id; ?>" title="Rename Semester"><i class="fa fa-pencil"></i></span>
											<span class="text-primary delSemester" data-sem-val="<?php echo $semester->id; ?>" title="Remove Semester"><i class="fa fa-times"></i></span>
										</div><?php
									}
								} ?>
							</div>
						</div>
					</div><?php
				} ?>
				
				<div class="tab-pane fade <?php if($this->session->get("user-role") == 2){ echo 'in active'; } ?>" id="grade-notifications">
					<div id="notification-box">
						<h3><i class="fa fa-envelope"></i> Grading Notifications</h3>
						<!-- notes and instruction -->
						<p>
							The Grading Notifications tool is to help Character Coaches alert and remind students &amp; their school staff to login and grade their students on whatever character traits it is time to grade on. Simply select the checkbox next to the character trait, then select which staff members you would like send the messages to (teachers, turf coaches &amp; students). Then the system will email all selected staff. When starting a new year, simply click the "Reset Notifications" button to uncheck all the character traits and start fresh.
						</p>
						
						<?php
						if($school){ 
							echo '<h4 id="school-name-h4" style="margin: 20px 0 15px;">'.$school->schoolName.' ('.$school->city.', '.$school->state.')</h4>';
							echo '<input type="hidden" id="selected-school" value="'.$school->id.'" />';
							//-- unserialize the notifications array --//
							if($school->notifications){
								$notifications = unserialize($school->notifications);
								if(!is_array($notifications)){
									$notifications = array('grit' => 0, 'focus' => 0, 'optimism' => 0, 'curiosity' => 0, 'leadership' => 0, 'energy' => 0, 'courage' => 0, 'initiative' => 0, 'social' => 0, 'humility' => 0, 'integrity' => 0, 'creativity' => 0);
								}
							}
						}else if(isset($schools) && $schools){ ?>
							<div class="form-group">	
								<label for="selected-school">School</label>
								<select id="selected-school" name="select-school" class="form-control">
									<option value="">Select School</option>
									<?php
										$curState = '';
										foreach($schools as $school){
											if($school->state != $curState){
												if($curState){
													echo '</optgroup><optgroup label="'.$states[$school->state].'">';
												}else{
													echo '<optgroup label="'.$states[$school->state].'">';
												}
												$curState = $school->state;
											}
											echo '<option value="'.$school->id.'">'.$school->schoolName.' ('.$school->city.', '.$school->state.')</option>';
										}
										echo '</optgroup>';
									?>
								</select>
							</div><?php
						} ?>
						
						<!-- Track Notifications Table -->
						<div id="display-results" class="col-md-6" style="padding-left: 0;">

							<table class="table table-hover table-bordered" style="max-width: 250px;">
								<thead>
									<tr>
										<th style="width: 30px;">&nbsp;</th>
										<th>Character Trait</th>
									</tr>
								</thead>
								<tbody>
									<?php
									if(isset($traits) && $traits){
										foreach($traits as $trait){ ?>
											<tr>
												<td style="width: 30px;">
													<input type="checkbox" class="select-trait" id="trait-<?php echo $trait->url_name; ?>" name="select-trait[]" value="<?php echo $trait->url_name; ?>" <?php if(isset($notifications) && $notifications[$trait->url_name]){ echo 'checked="checked"'; } ?> />
												</td>
												<td><?php
													echo $trait->trait_name;
													if(isset($notifications) && $notifications[$trait->url_name]){
														echo '<span class="label label-primary resend-note" data-trait="'.$trait->url_name.'" style="float: right; padding: 3px 5px 4px;">Resend</span>';
													} ?>
												</td>
											</tr><?php
										}
									}else{ ?>
										<tr><td colspan="2">No Results</td></tr><?php
									} ?>
								</tbody>
							</table>

						</div><!-- /#display-results -->
						
						<div class="col-md-6" style="padding: 0;">
							<div class="portlet">
								<div class="portlet-header">
									<h3><i class="fa fa-envelope"></i> Parent Notifications</h3>
								</div> <!-- /.portlet-header -->
								<div class="portlet-content">
									<p>
										Send notifications to remind parents to login and grade. Emails will be sent to all parents that are tied to students in your school.
									</p>
									<p class="text-primary">
										<span style="font-weight: bold; letter-spacing: 0.3px;">*Important Note:</span> When parents login to grade their students, they can only grade on the character traits that are checked.
									</p>
									<p style="text-align: center;">
										<span class="btn btn-secondary" id="notify-parents">Notify Parents</span>
									</p>
								</div> <!-- /.portlet-content -->
							</div> <!-- /.portlet -->
						</div>
						
						<p style="clear: left; float: left;">
							<span class="btn btn-primary" id="reset-notifications">Reset Notifications</span>
						</p>
						<div style="clear: both;">&nbsp;</div>
						
					</div>
				</div>
			</div>

		</div> <!-- /.col -->
		
	</div><!-- end #content-container -->

<?php
	//-- Footer --//
	$this->partial("partials/footer-top");
	$this->partial("partials/scripts/grading-management");
	$this->partial("partials/footer-bottom");
?>