<?php

//-- PHP Includes --//
include "inc/states.php";

//-- Page Vars --//
$page_title = 'Grade Students';


	//-- Pull in Header --//
	Phalcon\Tag::appendTitle($page_title);
	$this->partial("partials/header-top");
	$this->partial("partials/styles/default");
	$this->partial("partials/header-bottom");

	//-- Page Content Title --//
	echo '<div id="content-header"><h1>'.$page_title.'</h1></div><!-- #content-header -->';

	//-- Page Content --// ?>
	<div id="content-container">
		
		<?php $this->flashSession->output(); ?>
		
		<?php
		//-- Only give permissions if not a turfcoach, or if the turfcoach has been given permissions --//
		if($this->session->get("user-role") != 4 || isset($gradeLimit)){ ?>
			
			<div id="controlBar" class="col-md-12">
				<?php if(true == false){ ?>
						<div id="bulk-actions" class="btn-group" style="margin-right: 5px;" title="Bulk Actions">
							<button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown">
								<i class="fa fa-reorder"></i> <span class="bulk-txt">Bulk Actions</span> <span class="caret"></span>
							</button>
							<ul class="dropdown-menu" role="menu">
								<li><a href="javascript:;" onclick="$(this).getCSV();">Export CSV Template</a></li>
								<li><a href="javascript:;" onclick="jQuery('#importGradesModal').modal('show');">Import Grading Template</a></li>
							</ul>
						</div><!-- /#bulk-actions -->
				<?php } ?>
				
				<?php if($this->session->get("user-role") < 4){ ?>
					<!-- Report Cards -->
					<span id="generate-report-cards" class="btn btn-primary" title="Report Cards" style="margin-right: 5px;"><i class="fa fa-tasks"></i> <span>Report Cards</span></span>
					<form id="reportcards-form" action="/grading/reportcard" method="post" target="_blank" style="display: inline;">
						<input type="hidden" name="action" value="generate-reportcards" />
						<input type="hidden" name="cards" id="card-ids" value="" />
					</form>
				<?php } ?>
				
				<?php
				//-- Show / Hide Filters --//
				if(( ((isset($schoolID) && $schoolID) && $this->session->get("user-role") == 1) || isset($gradeID) || isset($searchTerm) || isset($missingGradeRole) || (isset($teacherID) && $teacherID) ) && $this->session->get("user-role") != 3 && $this->session->get("user-role") != 5){
					$filterText = 'Hide Filters';
					$showFilters = 'style="display: block;"';
				}else{
					$filterText = 'Show Filters';
					$showFilters = '';
				}
				if($this->session->get("user-role") != 3 && $this->session->get("user-role") != 5){ ?>
					<div id="show-user-filters" class="btn-group" title="Filters" style="margin-right: 5px;">
						<a href="#" class="btn btn-secondary"><i class="fa fa-filter"></i> <span><?php echo $filterText; ?></span></a>
					</div><?php
				} ?>
				
				<!-- Show Legend Button -->
				<span onclick="jQuery('#gradeLegendModal').modal('show');" id="grading-key" class="btn btn-info" title="Grading Key" style="margin-right: 5px;"><i class="fa fa-key"></i> <span>Key</span></span>
				
				<!-- Refresh Button -->
				<!--<a href="" id="refresh-ctrl-btn" class="btn btn-success" title="Refresh Page" style="margin-right: 5px;"><i class="fa fa-refresh"></i> <span>Refresh</span></a>-->
				<div class="btn-group" title="Refresh" style="margin-right: 5px;">
					<form id="refresh-page" action="" method="post">
						<span class="btn btn-success" id="refresh-ctrl-btn" onclick="jQuery('#refresh-page').submit();"><i class="fa fa-refresh"></i> <span>Refresh</span></span>
						<?php echo $inputs.$filters; ?>
					</form>
				</div>
				
				<div class="limit-results" title="Display Limit" style="float: right;">
					<form id="changeLimit" action="" method="post">
						<div id="bulk-actions" class="btn-group">
							<button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">
								<span id="limit-display-txt">Display &nbsp;</span><span class="badge badge-tertiary"><?php echo $limit; ?></span> <span class="caret"></span>
							</button>
							<ul class="dropdown-menu" role="menu">
								<?php
									$numRes = array(10, 25, 50);
									foreach($numRes as $num){ ?>
										<li><a href="#" data-val="<?php echo $num; ?>"><?php echo $num; ?></a></li><?php
									}
								?>
							</ul>
							<input type="hidden" name="limit" id="theLimit" class="form-control" value="<?php echo $limit; ?>" />
						</div>
						<?php echo $inputs.$schoolFilter.$gradeFilter.$teacherFilter.$missingGradeFilter.$missingTraitFilter.$searchFilter; ?>
					</form>
				</div><!-- /.limit-results -->

				<!-- Filters -->
				<div id="user-filters" class="well" <?php echo $showFilters; ?>>
					<?php //-- school filter --//
					if($schools && $this->session->get("user-role") == 1){ ?>
						<div class="filter-school col-sm-6">
							<form id="schoolFilter" action="" method="post">
								<label for="filter-schools">School Filter</label>
								<select name="filterSchool" id="filter-schools" class="form-control" onchange="jQuery('#schoolFilter').submit();">
									<option value="">Select School</option>
									<?php
										//-- List Out Schools --//
										$curState = '';
										foreach($schools as $school){
											if($school->state != $curState){
												if($curState){
													echo '</optgroup><optgroup label="'.$states[$school->state].'">';
												}else{
													echo '<optgroup label="'.$states[$school->state].'">';
												}
												$curState = $school->state;
											}
											if(isset($schoolID) && $school->id == $schoolID){ $sel = 'selected="selected"'; }else{ $sel = ''; }
											echo '<option value="'.$school->id.'" '.$sel.'>'.$school->schoolName.' ('.$school->city.', '.$school->state.')</option>';
										}
										echo '</optgroup>';
									?>
								</select>
								<?php echo $inputs.$limitFilter.$gradeFilter.$teacherFilter.$missingGradeFilter.$missingTraitFilter.$searchFilter; ?>
							</form>
						</div><?php
					}
					//-- grade filter --//
					if(isset($grade_level) && $grade_level){ ?>
						<div class="filter-grade col-sm-6">
							<form id="gradeFilter" action="" method="post">
								<label for="filter-grade">Grade Level Filter</label>
								<select name="filterGrade" id="filter-grade" class="form-control" onchange="jQuery('#gradeFilter').submit();">
									<option value="">Select Grade Level</option>
									<?php
										//-- List Out Grade Levels --//
										foreach($grade_level as $grade){
											if(isset($gradeID) && $grade->id == $gradeID){ $sel = 'selected="selected"'; }else{ $sel = ''; }
											//-- change grade list for turfcoaches --//
											if($this->session->get("user-role") == 4 && isset($gradeLimit)){
												if(in_array($grade->id, $gradeLimit)){
													echo '<option value="'.$grade->id.'" '.$sel.'>'.$grade->gradeName.'</option>';
												}
											}else{
												echo '<option value="'.$grade->id.'" '.$sel.'>'.$grade->gradeName.'</option>';
											}
										}
									?>
								</select>
								<?php echo $inputs.$limitFilter.$schoolFilter.$missingGradeFilter.$missingTraitFilter.$searchFilter; ?>
							</form>
						</div><?php
					}
					//-- teacher filter --//
					if(isset($teacherList)){ ?>
						<div class="filter-teacher col-sm-6">
							<form id="teacherFilter" action="" method="post">
								<label for="filter-teacher">Teacher Filter</label>
								<select name="filterTeacher" id="filter-teacher" class="form-control" onchange="jQuery('#teacherFilter').submit();">
									<option value="">Select Teacher</option>
									<?php
										//-- List Out Teachers --//
										foreach($teacherList as $teacher){
											if(isset($teacherID) && $teacher->id == $teacherID){ $sel = 'selected="selected"'; }else{ $sel = ''; }
											echo '<option value="'.$teacher->id.'" '.$sel.'>'.$teacher->lname.', '.$teacher->fname.'</option>';
										}
									?>
								</select>
								<?php echo $inputs.$limitFilter.$schoolFilter.$gradeFilter.$missingGradeFilter.$missingTraitFilter.$searchFilter; ?>
							</form>
						</div><?php
					} ?>
					
					<!-- Search Filter -->
					<div id="filter-search" class="col-sm-6">
						<form id="searchFilter" action="" method="post">
							<label for="searchTerm">Search Students Filter</label>
							<div class="input-group">
								<input type="text" name="filterSearch" id="searchTerm" class="form-control" placeholder="Enter First or Last Name" value="<?php if(isset($searchTerm) && $searchTerm != ''){ echo $searchTerm; } ?>">
								<div class="input-group-btn">
									<button type="button" class="btn btn-tertiary" onclick="jQuery('#searchFilter').submit();"><i class="fa fa-search"></i> Search</button>
								</div><!-- /input-group-btn -->
							</div><!-- /input-group -->
							<?php echo $inputs.$limitFilter.$schoolFilter.$gradeFilter.$teacherFilter.$missingGradeFilter.$missingTraitFilter; ?>
						</form>
					</div>
					<!-- End Search Filter -->
					
					<?php
					//-- Grade Missing Filter --//
					if($this->session->get("user-role") <= 2 && (isset($missingGradeRole) || (isset($schoolID) && (isset($teacherID) || isset($gradeID))))){ ?>
						<div class="col-sm-12" style="clear: both;">
							<h3 class="heading" style="margin: 0 0 5px; padding: 10px 0 7px; font-size: 15px;">
								<i class="fa fa-cog">&nbsp; Advanced Filters</i>
							</h3>
						</div>
						<div class="filter-missing-grade col-sm-6">
							<form id="missingGradeFilter" action="" method="post">
								<label for="filter-missing-grade">Student Not Yet Graded Filter</label>
								<select name="filterMissingGrade" id="filter-missing-grade" class="form-control" onchange="jQuery('#missingGradeFilter').submit();">
									<option value="">Select Missing Grade</option>
									<?php
										//-- List Out Missing Grade Roles --//
										$gradeRoles = array('3' => 'Teacher', '4' => 'Turf Coach', '0' => 'Student', '5' => 'Parent');
										foreach($gradeRoles as $gkey => $grole){
											if(isset($missingGradeRole) && $gkey == $missingGradeRole){ $sel = 'selected="selected"'; }else{ $sel = ''; }
											echo '<option value="'.$gkey.'" '.$sel.'>'.$grole.' Grade</option>';
										}
									?>
								</select>
								<?php echo $inputs.$limitFilter.$schoolFilter.$gradeFilter.$teacherFilter.$missingTraitFilter.$searchFilter; ?>
							</form>
						</div>
						<?php
						if(isset($missingGradeRole)){ ?>
							<div class="filter-missing-trait col-sm-6">
								<form id="missingTraitFilter" action="" method="post">
									<label for="filter-missing-trait">Character Traits - Missing Grade</label>
									<select name="filterMissingTrait" id="filter-missing-trait" class="form-control" onchange="jQuery('#missingTraitFilter').submit();">
										<option value="">Select Performance Character Trait</option>
										<?php
											//-- List Out Missing Grade Roles --//
											foreach($traits as $trait){
												if(isset($missingTrait) && $trait->url_name == $missingTrait){ $sel = 'selected="selected"'; }else{ $sel = ''; }
												echo '<option value="'.$trait->url_name.'" '.$sel.'>'.$trait->trait_name.' Grade</option>';
											}
										?>
									</select>
									<?php echo $inputs.$limitFilter.$schoolFilter.$gradeFilter.$teacherFilter.$missingGradeFilter.$searchFilter; ?>
								</form>
							</div><?php
						}
					} ?>
					<div class="clear"></div>
				</div>
				<!-- end filters -->

			</div><!-- /#controlBar -->

			<div id="display-results" class="col-md-12">

				<table class="table table-hover table-bordered">
					<thead>
						<tr>
							<th style="width: 30px;">
								<input type="checkbox" id="check-all" />
							</th>
							<?php
							//-- if admin or char. coach --//
							if($this->session->get("user-role") < 3){ ?>
								<th style="width: 30px;"></th><?php
							} ?>
							<th>
								<form id="form1" action="" method="post">
									<input type="hidden" name="field" value="firstname" />
									<span onclick="jQuery('#form1').submit();">First Name</span>
									<?php
									echo $lastField;
									if($field == 'firstname'){ echo '<i class="fa fa-sort-'.$dir.'"></i>'; }
									?>
								</form>
							</th>
							<th>
								<form id="form2" action="" method="post">
									<input type="hidden" name="field" value="lastname" />
									<span onclick="jQuery('#form2').submit();">Last Name</span>
									<?php
									echo $lastField;
									if($field == 'lastname'){ echo '<i class="fa fa-sort-'.$dir.'"></i>'; }
									?>
								</form>
							</th>
							<th class="hideable">
								<form id="form3" action="" method="post">
									<input type="hidden" name="field" value="grade_level" />
									<span onclick="jQuery('#form3').submit();">Grade Level</span>
									<?php
									echo $lastField;
									if($field == 'grade_level'){ echo '<i class="fa fa-sort-'.$dir.'"></i>'; }
									?>
								</form>
							</th>
							<th class="hideable">
								<form id="form4" action="" method="post">
									<input type="hidden" name="field" value="teacher" />
									<span onclick="jQuery('#form4').submit();">Teacher</span>
									<?php
									echo $lastField;
									if($field == 'teacher'){ echo '<i class="fa fa-sort-'.$dir.'"></i>'; }
									?>
								</form>
							</th>
							<th></th>
						</tr>
					</thead>
					<tbody>
						<?php
						
						if(count($students) > 0){
							foreach($students as $student){
								//-- See if grade has been entered for student --//
								if(($this->session->get("user-role") == 3 || $this->session->get("user-role") == 4) && !isset($missingGradeRole)){
									$completed = true;
									$graded = $student->getGrading(array("semester = :sem: AND eval_role = :role:", "bind" => array("sem" => $this->session->get("current-semester"), "role" => $this->session->get("user-role"))));
									if(count($graded) > 0){
										foreach($graded as $grade){
											if($student->grade > 3){
												//-- Upper Grades check to see if grade exists --//
												if(is_array($reqNote)){
													foreach($reqNote as $key => $val){
														if(!$grade->{$key}){
															$completed = false;
															break;
														}
													}
												}
											}else{
												//-- Lower Grades check to see if observation exists --//
												$observations = unserialize($grade->observations);
												if(is_array($observations) && is_array($reqNote)){
													foreach($reqNote as $key => $val){
														if(!$observations[$key]){
															$completed = false;
															break;
														}
													}
												}
											}
										}
									}else{
										//-- No Grades --//
										if(!empty($reqNote)){
											$completed = false;
										}
									}
								}else{
									$completed = true;
								} ?>
								<tr <?php if(!$completed){ echo 'style="font-weight: bold;"'; } ?>>
									<td style="width: 30px;">
										<input type="checkbox" class="select-check" name="select-user[]" value="<?php echo $student->id; ?>" />
									</td>
									<?php
									//-- if admin or char. coach --//
									if($this->session->get("user-role") < 3){
										echo '<td>';
										if($student->grade > 3){
											//-- Grab # of times graded & total grade --//
											$query = "SELECT AVG(grade) FROM (
												SELECT semester, student, grit grade FROM grading WHERE grit != 0 UNION ALL
												SELECT semester, student, focus FROM grading WHERE focus != 0 UNION ALL
												SELECT semester, student, optimism FROM grading WHERE optimism != 0 UNION ALL
												SELECT semester, student, curiosity FROM grading WHERE curiosity != 0 UNION ALL
												SELECT semester, student, leadership FROM grading WHERE leadership != 0 UNION ALL
												SELECT semester, student, energy FROM grading WHERE energy != 0 UNION ALL
												SELECT semester, student, courage FROM grading WHERE courage != 0 UNION ALL
												SELECT semester, student, initiative FROM grading WHERE initiative != 0 UNION ALL
												SELECT semester, student, social FROM grading WHERE social != 0 UNION ALL
												SELECT semester, student, humility FROM grading WHERE humility != 0 UNION ALL
												SELECT semester, student, integrity FROM grading WHERE integrity != 0 UNION ALL
												SELECT semester, student, creativity FROM grading WHERE creativity != 0
												) t WHERE student = :sID AND semester = :sem";
											$result = $this->db->query($query, array('sID' => $student->id, 'sem' => $this->session->get("current-semester")));
											//echo $result->numRows();
											$result->setFetchMode(Phalcon\Db::FETCH_NUM);
											while($aGrade = $result->fetchArray()){
												//print_r($aGrade);
											    echo '<span class="label label-primary">'.round($aGrade[0], 1, PHP_ROUND_HALF_UP).'</span>';
											}
										}
										echo '</td>';
									} ?>
									<td><?php echo $student->fname; ?></td>
									<td><?php echo $student->lname; ?></td>
									<?php
									if(isset($grade_level) && $grade_level){ ?>
										<td class="hideable"><?php echo $grade_level[$student->grade]->gradeName; ?></td><?php
									}else{ ?>
										<td class="hideable"><?php echo $student->grade; ?></td><?php
									}
									if(isset($teacherRef) && $teacherRef){ ?>
										<td class="hideable"><?php echo $teacherRef[$student->teacher]; ?></td><?php
									}else{ ?>
										<td class="hideable"><?php echo $student->teacher; ?></td><?php
									} ?>

									<td style="min-width: 180px;">
										<?php
										//-- Actions for Admins & Char. Coaches --//
										if($this->session->get("user-role") < 3){?>
											<span class="label label-info reviewGrades" data-student-val="<?php echo $student->id; ?>" data-student-name="<?php echo $student->fname.' '.$student->lname; ?>" data-grade-level="<?php echo $student->grade; ?>"><i class="fa fa-dot-circle-o"></i> Review Grades</span><?php
										}else if($this->session->get("user-role") == 3 || $this->session->get("user-role") == 4){ ?>
											<span class="label label-primary gradeStudent" data-student-val="<?php echo $student->id; ?>" data-student-name="<?php echo $student->fname.' '.$student->lname; ?>" data-grade-level="<?php echo $student->grade; ?>"><i class="fa fa-check"></i> Enter Grades</span><?php
										} ?>
									</td>
								</tr><?php
							}
						}else{
							//-- if admin or char. coach --//
							if($this->session->get("user-role") < 3){ ?>
								<tr><td colspan="7">No Results</td></tr><?php
							}else{ ?>
								<tr><td colspan="6">No Results</td></tr><?php
							}
						} ?>
					</tbody>
				</table>

			</div><!-- /#display-results -->

			<div class="col-md-12">

				<?php
				//-- Create Pager --//
				if($totalStudents > $limit){
					//-- Calculations --//
					$numLimit = $totalStudents / $limit;
					$curMin = (($pageNum - 1) * $limit) + 1;
					$curMax = $pageNum * $limit;
					if($curMax > $totalStudents){ $curMax = $totalStudents; }

					echo '<div class="users-pager">';
					echo '<span class="page-count">Showing <span class="curMin">'.$curMin.'</span> - <span class="curMax">'.$curMax.'</span> of '.$totalStudents.' Students</span>';
					echo '<ul class="pagination" data-limit="'.$limit.'" data-total="'.$totalStudents.'">';
					if($pageNum == 1){ $prevClass = 'disabled'; }else{ $prevClass = ''; }
					echo '<li class="prev '.$prevClass.'"><a href="#">← Previous</a></li>';
					$i = 0;
					while($i < $numLimit){
						$i++;
						if($i == $pageNum){ $theClass = 'active '; }else{ $theClass = ''; }
						if($i == 1){ $theClass.= 'firstPage '; }
						if($i >= $numLimit){ $theClass.= 'lastPage '; }
						if(!$theClass && $numLimit > 5 && ($i > ($pageNum + 2) || $i < ($pageNum - 2))){ $theClass.= 'scrunch '; }
						echo '<li class="'.$theClass.'"><a href="#" data-page="'.$i.'">'.$i.'</a></li>';
					}
					if($curMax == $totalStudents){ $nextClass = 'disabled'; }else{ $nextClass = ''; }
					echo '<li class="next '.$nextClass.'"><a href="#">Next → </a></li></ul>';
					echo '</div>'; ?>

					<form id="pagerForm" action="" method="post">
						<input type="hidden" name="pageNum" id="pageNumber" value="<?php echo $pageNum; ?>" />
						<?php echo $inputs.$limitFilter.$schoolFilter.$gradeFilter.$teacherFilter.$missingGradeFilter.$missingTraitFilter.$searchFilter; ?>
					</form><?php
				} ?>

			</div><?php
			
		}else{ ?>
			<div class="alert alert-danger">
				<a class="close" data-dismiss="alert" href="#" aria-hidden="true">×</a>
				<strong style="letter-spacing: 0.3px;">No Grading Permissions</strong> Contact your school's character coach about getting assigned grading permissions.
			</div><?php
		} ?>

	</div><!-- end #content-container -->

<?php
	//-- Footer --//
	$this->partial("partials/footer-top");
	$this->partial("partials/scripts/grading");
	$this->partial("partials/footer-bottom");
?>