<?php

//-- Page Vars --//
$page_title = 'Grade: '.$this->session->get("student-name");


	//-- Pull in Header --//
	Phalcon\Tag::appendTitle($page_title);
	$this->partial("partials/header-top");
	$this->partial("partials/styles/default");
	$this->partial("partials/header-bottom");

	//-- Page Content Title --//
	echo '<div id="content-header"><h1>'.$page_title.'</h1></div><!-- #content-header -->';

	//-- Page Content --// ?>
	<div id="content-container">
		
		<?php $this->flashSession->output(); ?>
		
		<div class="alert alert-info">
			<a class="close" data-dismiss="alert" href="#" aria-hidden="true">×</a>
			<strong>Let's Grade!</strong> &nbsp;Listed below are all the character traits that are open for grading. As the year progresses, more character traits will become available for grading.
		</div>
		
		<p><strong>Grading Instructions:</strong></p>
		<ol>
			<li>Select the character trait you would like to grade. The grading form should appear.</li>
			<li>Input a numeric grade (1 - 5) in the small box above the submit button, or drag the slider to grade the character trait.
				<span class="label label-info" onclick="jQuery('#gradeLegendModal').modal('show');" style="font-size: 11px; cursor: pointer;"><i class="fa fa-key"></i> Grading Key</span>
			</li>
			<li>Click the submit button to submit the grade.</li>
			<li>A success message will appear in the bottom right corner of your screen if grade was successfully entered.</li>
		</ol>
		
		<?php
		//-- If grading traits are available --//
		if(isset($notes) && is_array($notes)){ ?>
			
			<div class="form-group" style="margin: 0 auto; padding: 5px 0 0; width: 80%;">
				<label for="pick-trait">Character Trait</label><br />
				<select class="form-control pick-trait" data-student="<?php echo $this->session->get("student-id"); ?>">
					<option value="">Select Character Trait</option><?php
					//-- List out all available character traits to grade --//
			 		foreach($notes as $key => $val){
						echo '<option value="'.$traitList[$key]['id'].'">'.$traitList[$key]['name'].'</option>';
					} ?>
				</select>
			</div>
				
			<div id="grading-form-<?php echo $this->session->get("student-id"); ?>" class="sp-grading-form" style="clear: both; margin: 20px 0 0; float: none; padding: 10px 0 0; display: none; border-top: 1px solid #eaeaea;">
				<div class="form-group" style="padding-top: 15px;">
					<div class="col-sm-12">
						<label for="trait-grade-<?php echo $this->session->get("student-id"); ?>" style="font-size: 24px;">
							<i class="fa"></i> <span class="trait-name"></span>
						</label>
						<blockquote style="margin: 0 0 10px;">
							<p class="trait-description" style="font-size: 12px;"></p>
						</blockquote>
					</div>
					<div class="gradeSection" <?php if($this->session->get("student-grade") < 4){ echo 'style="display: none;"'; } ?>>
						<div class="col-sm-9">
							<div class="incrementSlider slider-secondary" style="margin-top: 1em;"></div>
						</div>
						<div class="col-sm-3">
							<input type="text" onkeyup="this.value = this.value.replace(/[^0-5]/g,'');" class="form-control grade-input" id="trait-grade-<?php echo $this->session->get("student-id"); ?>" maxlength="1" style="width: 34px;" value="">
						</div>
					</div>
					<div class="col-sm-9 observationSection">
						<textarea class="form-control grade-observation" rows="2" cols="10" placeholder="Enter Observations..." style="display: none;"></textarea>
					</div>
					<div class="col-sm-3">
						<span class="btn btn-primary submitYourGrade" style="margin: 19px 0 0;" data-grade-val="" data-student-val="" data-trait="" data-grade-level="<?php echo $this->session->get("student-grade"); ?>">Submit</span>
					</div>
					<div style="clear: both;"></div>
				</div>
			</div><?php
			
		}else{
			//-- Error Message - Grading not open yet. --// ?>
			<div class="alert alert-danger">
				<a class="close" data-dismiss="alert" href="#" aria-hidden="true">×</a>
				<strong>Grading Not Available</strong> &nbsp;No Character Traits are open for grading for your school. If this is incorrect, please contact your school's character coach.
			</div><?php
		} ?>
		
	</div><!-- end #content-container -->

<?php
	//-- Footer --//
	$this->partial("partials/footer-top");
	$this->partial("partials/scripts/grading");
	$this->partial("partials/footer-bottom");
?>