<?php

//-- Page Vars --//
$page_title = 'Verify Child Guardianship';


	//-- Pull in Header --//
	Phalcon\Tag::appendTitle($page_title);
	$this->partial("partials/header-top");
	$this->partial("partials/styles/default");
	$this->partial("partials/header-bottom");

	//-- Page Content Title --//
	echo '<div id="content-header"><h1>'.$page_title.'</h1></div><!-- #content-header -->';

	//-- Page Content --// ?>
	<div id="content-container">
		
		<?php $this->flashSession->output(); ?>
		
		<div class="alert alert-info">
			<a class="close" data-dismiss="alert" href="#" aria-hidden="true">×</a>
			<strong>Before you can enter grades for a student</strong> you must have been added as a parent of the child, and then you must verify your guardianship for the child.
		</div>
		<div class="alert alert-warning">
			<a class="close" data-dismiss="alert" href="#" aria-hidden="true">×</a>
			<strong>If you are missing a child</strong>, and that student has not been added for you to verify, contact the character coach at your school.
		</div>
		<div class="divider" style="border-top: 1px solid #eaeaea; height: 30px;">&nbsp;</div>
		<blockquote>
			<p style="font-size: 14px;">
				<strong style="position: relative; bottom: 3px;">Instructions:</strong><br>
				To verify your relationship with each student/child simply go to their name and click the button labeled 'Verify Relationship'
			</p>
		</blockquote>
		<br>
		
		
		<?php
			//-- Add Navigation --//
			if(count($relationships) > 0){ ?>
				<div class="col-md-3 col-sm-5">
					<ul class="nav nav-pills nav-stacked"><?php
					$i = 0;
					foreach($relationships as $rel){
						$curStudent = $students[$rel->student]; ?>
						<li class="<?php if($i == 0){ echo 'active'; } ?>">
							<a href="#student-<?php echo $curStudent->id; ?>" data-toggle="tab"><i class="fa fa-user"></i> &nbsp;&nbsp;<?php echo $curStudent->fname." ".$curStudent->lname; ?></a>
						</li><?php
						$i++;
					} ?>
					</ul>
				</div><!-- /.col --><?php
			}
			
			
			//-- Add Tabbed Content --//
			if(count($relationships) > 0){ ?>
				<div class="col-md-9 col-sm-7">
					<div class="tab-content stacked-content"><?php
			
				$i = 0;
				foreach($relationships as $rel){
					$curStudent = $students[$rel->student];
					//-- if stacking content - add its container div --// ?>
						<div class="tab-pane fade <?php if($i == 0){ echo 'in active'; } ?>" id="student-<?php echo $curStudent->id; ?>">

							<h3><i class="fa fa-user"></i> <span class="student-name"><?php echo $curStudent->fname." ".$curStudent->lname; ?></span></h3>
							 
								<?php
									if($rel->verified){ ?>
										<p class="relationship" style="font-size: 15px;">
											Relationship: &nbsp; <span class="rel-status text-success"><i class="fa fa-check"></i> <span>Verified</span></span>
										</p>
										<p><span class="btn btn-danger remove-child" data-rel-val="<?php echo $rel->id; ?>"><i class="fa fa-thumbs-down"></i> Not My Student</span></p><?php
									}else{ ?>
										<p class="relationship" style="font-size: 15px;">
											Relationship: &nbsp; <span class="rel-status text-primary"><i class="fa fa-ban"></i> <span>Not Verified</span></span>
										</p>
										<p>
											<span class="btn btn-success verify-child" data-rel-val="<?php echo $rel->id; ?>" style="margin-right: 5px;"><i class="fa fa-thumbs-up"></i> Verify Relationship</span>
											<span class="btn btn-primary remove-child" data-rel-val="<?php echo $rel->id; ?>"><i class="fa fa-thumbs-down"></i> Not My Student</span>
										</p><?php
									}
								?>
							
						</div><?php
					$i++;
				} //-- end foreach() --// ?>
			
					</div>
				</div> <!-- /.col --><?php
			} ?>

		
	</div><!-- end #content-container -->

<?php
	//-- Footer --//
	$this->partial("partials/footer-top");
	$this->partial("partials/scripts/grading-verify");
	$this->partial("partials/footer-bottom");
?>