<?php

//-- Page Vars --//
$page_title = 'Manage Parents';


	//-- Pull in Header --//
	Phalcon\Tag::appendTitle($page_title);
	$this->partial("partials/header-top");
	$this->partial("partials/styles/default");
	$this->partial("partials/header-bottom");

	//-- Page Content Title --//
	echo '<div id="content-header"><h1>'.$page_title.'</h1></div><!-- #content-header -->';

	//-- Page Content --// ?>
	<div id="content-container">
		
		<?php $this->flashSession->output(); ?>
		
		<div id="controlBar" class="col-md-12">
			<!-- add User Btn -->
			<span class="btn btn-primary" onclick="jQuery('#addUserModal').modal('show');" title="Add Parent" style="margin-right: 5px;"><i class="fa fa-plus"></i></span>
			
			<div id="bulk-actions" class="btn-group" title="Bulk Actions" style="margin-right: 5px;">
				<button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown">
					<i class="fa fa-reorder"></i> <span class="bulk-txt">Bulk Actions</span> <span class="caret"></span>
				</button>
				<ul class="dropdown-menu" role="menu">
					<li><a href="javascript:;" onclick="$(this).getCSV();">Export CSV File</a></li>
					<li><a href="javascript:;" onclick="jQuery('#importCSVModal').modal('show');">Import CSV File</a></li>
				</ul>
			</div><!-- /#bulk-actions -->
			
			<!-- Refresh Button -->
			<div class="btn-group" title="Refresh Page" style="margin-right: 5px;">
				<form id="refresh-page" action="" method="post">
					<span class="btn btn-success" id="refresh-ctrl-btn" onclick="jQuery('#refresh-page').submit();"><i class="fa fa-refresh"></i> <span>Refresh</span></span>
					<?php echo $inputs.$filters; ?>
				</form>
			</div>
			
			<div class="limit-results" title="Display Limit" style="float: right;">
				<form id="changeLimit" action="" method="post">
					<div id="bulk-actions" class="btn-group">
						<button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">
							<span id="limit-display-txt">Display &nbsp;</span><span class="badge badge-tertiary"><?php echo $limit; ?></span> <span class="caret"></span>
						</button>
						<ul class="dropdown-menu" role="menu">
							<?php
								$numRes = array(10, 25, 50);
								foreach($numRes as $num){ ?>
									<li><a href="#" data-val="<?php echo $num; ?>"><?php echo $num; ?></a></li><?php
								}
							?>
						</ul>
						<input type="hidden" name="limit" id="theLimit" class="form-control" value="<?php echo $limit; ?>" />
					</div>
					<?php echo $inputs; ?>
				</form>
			</div><!-- /.limit-results -->
		</div><!-- /#controlBar -->
		
		<div id="display-results" class="col-md-12">
			
			<table class="table table-hover table-bordered">
				<thead>
					<tr>
						<th style="width: 30px;">
							<input type="checkbox" id="check-all" />
						</th>
						<th class="hideable">
							<form id="form1" action="" method="post">
								<input type="hidden" name="field" value="username" />
								<span onclick="jQuery('#form1').submit();">User name</span>
								<?php
								echo $lastField;
								if($field == 'username'){ echo '<i class="fa fa-sort-'.$dir.'"></i>'; }
								?>
							</form>
						</th>
						<th>
							<form id="form2" action="" method="post">
								<input type="hidden" name="field" value="firstname" />
								<span onclick="jQuery('#form2').submit();">First Name</span>
								<?php
								echo $lastField;
								if($field == 'firstname'){ echo '<i class="fa fa-sort-'.$dir.'"></i>'; }
								?>
							</form>
						</th>
						<th>
							<form id="form3" action="" method="post">
								<input type="hidden" name="field" value="lastname" />
								<span onclick="jQuery('#form3').submit();">Last Name</span>
								<?php
								echo $lastField;
								if($field == 'lastname'){ echo '<i class="fa fa-sort-'.$dir.'"></i>'; }
								?>
							</form>
						</th>
						<th class="hideable">
							<form id="form4" action="" method="post">
								<input type="hidden" name="field" value="email" />
								<span onclick="jQuery('#form4').submit();">Email</span>
								<?php
								echo $lastField;
								if($field == 'email'){ echo '<i class="fa fa-sort-'.$dir.'"></i>'; }
								?>
							</form>
						</th>
						<th></th>
					</tr>
				</thead>
				<tbody>
					<?php
					if(count($parents) > 0){
						foreach($parents as $parent){ ?>
							<tr>
								<td style="width: 30px;">
									<input type="checkbox" class="select-check" name="select-user[]" value="<?php echo $parent->id; ?>" />
								</td>
								<td class="hideable"><?php echo $parent->usernm; ?></td>
								<td><?php echo $parent->fname; ?></td>
								<td><?php echo $parent->lname; ?></td>
								<td class="hideable"><?php echo $parent->email; ?></td>
								<td>
									<?php if($parent->usernm){ $user_name = $parent->usernm; }else{ $user_name = $parent->fname.' '.$parent->lname; } ?>
									<span class="label label-secondary editUser" data-user-val="<?php echo $parent->id; ?>"><i class="fa fa-pencil"></i> Edit</span>
									<span class="label label-tertiary delUser" data-user-val="<?php echo $parent->id; ?>" data-user-name="<?php echo $user_name; ?>"><i class="fa fa-ban"></i> Delete</span>
								</td>
							</tr><?php
						}
					}else{ ?>
						<tr><td colspan="6">No Results</td></tr><?php
					} ?>
				</tbody>
			</table>
			
		</div><!-- /#display-results -->
		
		<div class="col-md-12">
			
			<?php
			//-- Create Pager --//
			if($totalUsers > $limit){
				//-- Calculations --//
				$numLimit = $totalUsers / $limit;
				$curMin = (($pageNum - 1) * $limit) + 1;
				$curMax = $pageNum * $limit;
				if($curMax > $totalUsers){ $curMax = $totalUsers; }
				
				echo '<div class="users-pager">';
				echo '<span class="page-count">Showing <span class="curMin">'.$curMin.'</span> - <span class="curMax">'.$curMax.'</span> of '.$totalUsers.' Parents</span>';
				echo '<ul class="pagination" data-limit="'.$limit.'" data-total="'.$totalUsers.'">';
				if($pageNum == 1){ $prevClass = 'disabled'; }else{ $prevClass = ''; }
				echo '<li class="prev '.$prevClass.'"><a href="#">← Previous</a></li>';
				$i = 0;
				while($i < $numLimit){
					$i++;
					if($i == $pageNum){ $theClass = 'active '; }else{ $theClass = ''; }
					if($i == 1){ $theClass.= 'firstPage '; }
					if($i >= $numLimit){ $theClass.= 'lastPage '; }
					if(!$theClass && $numLimit > 5 && ($i > ($pageNum + 2) || $i < ($pageNum - 2))){ $theClass.= 'scrunch '; }
					echo '<li class="'.$theClass.'"><a href="#" data-page="'.$i.'">'.$i.'</a></li>';
				}
				if($curMax == $totalUsers){ $nextClass = 'disabled'; }else{ $nextClass = ''; }
				echo '<li class="next '.$nextClass.'"><a href="#">Next → </a></li></ul>';
				echo '</div>'; ?>
				
				<form id="pagerForm" action="" method="post">
					<input type="hidden" name="pageNum" id="pageNumber" value="<?php echo $pageNum; ?>" />
					<?php echo $inputs.$limitFilter; ?>
				</form><?php
			} ?>
			
		</div>
		
	</div><!-- /#content-container -->

<?php
	//-- Footer --//
	$this->partial("partials/footer-top");
	$this->partial("partials/scripts/user-management");
	$this->partial("partials/footer-bottom");
?>